// Kody wydziałów ksiąg wieczystych → sąd rejonowy (pkt 2: brak sądu w danych KW).
// Źródło: załącznik do rozporządzenia Ministra Sprawiedliwości z 28.10.2019 r.
// (Dz.U. 2019 poz. 2222) — 345 kodów. Ta sama lista jest w tabeli
// `kw_court_codes` (migracja 20261009120000_kw_court_codes.sql).
// Plik generowany z tekstu aktu — zmiany wprowadzaj w obu miejscach.

export interface KwCourtCode {
  /** Np. "Sąd Rejonowy w Słupsku". */
  sad: string;
  /** Wydział zamiejscowy, gdy kod go dotyczy. */
  wydzial?: string;
  /** Zakres terytorialny, gdy sąd ma kilka wydziałów KW (np. Warszawa-Mokotów). */
  zakres?: string;
}

export const KW_COURT_CODES_SOURCE = "Dz.U. 2019 poz. 2222";

export const KW_COURT_CODES: Readonly<Record<string, KwCourtCode>> = {
  BI1B: { sad: "Sąd Rejonowy w Białymstoku" },
  BI1P: { sad: "Sąd Rejonowy w Bielsku Podlaskim" },
  BI2P: {
    sad: "Sąd Rejonowy w Bielsku Podlaskim",
    wydzial: "Wydział Zamiejscowy z siedzibą w Hajnówce",
  },
  BI3P: {
    sad: "Sąd Rejonowy w Bielsku Podlaskim",
    wydzial: "Wydział Zamiejscowy z siedzibą w Siemiatyczach",
  },
  BI1S: { sad: "Sąd Rejonowy w Sokółce" },
  LM1G: { sad: "Sąd Rejonowy w Grajewie" },
  LM1L: { sad: "Sąd Rejonowy w Łomży" },
  LM1W: { sad: "Sąd Rejonowy w Wysokiem Mazowieckiem" },
  LM1Z: { sad: "Sąd Rejonowy w Zambrowie" },
  OL1Y: { sad: "Sąd Rejonowy w Bartoszycach" },
  OL1B: { sad: "Sąd Rejonowy w Biskupcu" },
  OL1G: { sad: "Sąd Rejonowy w Giżycku" },
  OL2G: { sad: "Sąd Rejonowy w Giżycku", wydzial: "Wydział Zamiejscowy z siedzibą w Węgorzewie" },
  OL1K: { sad: "Sąd Rejonowy w Kętrzynie" },
  OL1L: { sad: "Sąd Rejonowy w Lidzbarku Warmińskim" },
  OL1M: { sad: "Sąd Rejonowy w Mrągowie" },
  OL1N: { sad: "Sąd Rejonowy w Nidzicy" },
  OL1O: { sad: "Sąd Rejonowy w Olsztynie" },
  OL1P: { sad: "Sąd Rejonowy w Piszu" },
  OL1S: { sad: "Sąd Rejonowy w Szczytnie" },
  OS1O: { sad: "Sąd Rejonowy w Ostrołęce" },
  OS1M: { sad: "Sąd Rejonowy w Ostrowi Mazowieckiej" },
  OS1P: { sad: "Sąd Rejonowy w Przasnyszu" },
  OS1U: { sad: "Sąd Rejonowy w Pułtusku" },
  OS1W: { sad: "Sąd Rejonowy w Wyszkowie" },
  SU1A: { sad: "Sąd Rejonowy w Augustowie" },
  SU1N: { sad: "Sąd Rejonowy w Augustowie", wydzial: "Wydział Zamiejscowy z siedzibą w Sejnach" },
  OL1E: { sad: "Sąd Rejonowy w Ełku" },
  OL1C: { sad: "Sąd Rejonowy w Olecku" },
  SU1S: { sad: "Sąd Rejonowy w Suwałkach" },
  BY1B: { sad: "Sąd Rejonowy w Bydgoszczy" },
  BY1I: { sad: "Sąd Rejonowy w Inowrocławiu" },
  BY1M: { sad: "Sąd Rejonowy w Mogilnie" },
  BY1N: { sad: "Sąd Rejonowy w Nakle nad Notecią" },
  BY1U: { sad: "Sąd Rejonowy w Szubinie" },
  BY1S: { sad: "Sąd Rejonowy w Świeciu" },
  BY1T: { sad: "Sąd Rejonowy w Tucholi" },
  BY2T: {
    sad: "Sąd Rejonowy w Tucholi",
    wydzial: "Wydział Zamiejscowy z siedzibą w Sępólnie Krajeńskim",
  },
  BY1Z: { sad: "Sąd Rejonowy w Żninie" },
  EL1B: { sad: "Sąd Rejonowy w Braniewie" },
  EL1D: { sad: "Sąd Rejonowy w Działdowie" },
  EL1E: { sad: "Sąd Rejonowy w Elblągu" },
  EL1I: { sad: "Sąd Rejonowy w Iławie" },
  EL1N: { sad: "Sąd Rejonowy w Nowym Mieście Lubawskim" },
  EL1O: { sad: "Sąd Rejonowy w Ostródzie" },
  EL2O: { sad: "Sąd Rejonowy w Ostródzie", wydzial: "Wydział Zamiejscowy z siedzibą w Morągu" },
  GD1G: { sad: "Sąd Rejonowy Gdańsk-Północ w Gdańsku" },
  GD1Y: { sad: "Sąd Rejonowy w Gdyni" },
  GD1R: { sad: "Sąd Rejonowy w Kartuzach" },
  GD1E: { sad: "Sąd Rejonowy w Kościerzynie" },
  GD1I: { sad: "Sąd Rejonowy w Kwidzynie" },
  GD2I: { sad: "Sąd Rejonowy w Kwidzynie", wydzial: "Wydział Zamiejscowy z siedzibą w Sztumie" },
  GD1M: { sad: "Sąd Rejonowy w Malborku" },
  GD2M: {
    sad: "Sąd Rejonowy w Malborku",
    wydzial: "Wydział Zamiejscowy z siedzibą w Nowym Dworze Gdańskim",
  },
  GD1S: { sad: "Sąd Rejonowy w Sopocie" },
  GD1A: { sad: "Sąd Rejonowy w Starogardzie Gdańskim" },
  GD1T: { sad: "Sąd Rejonowy w Tczewie" },
  GD1W: { sad: "Sąd Rejonowy w Wejherowie" },
  GD2W: { sad: "Sąd Rejonowy w Wejherowie", wydzial: "Wydział Zamiejscowy z siedzibą w Pucku" },
  SL1B: { sad: "Sąd Rejonowy w Bytowie" },
  SL1C: { sad: "Sąd Rejonowy w Chojnicach" },
  SL1Z: { sad: "Sąd Rejonowy w Człuchowie" },
  SL1L: { sad: "Sąd Rejonowy w Lęborku" },
  SL1M: { sad: "Sąd Rejonowy w Miastku" },
  SL1S: { sad: "Sąd Rejonowy w Słupsku" },
  TO1B: { sad: "Sąd Rejonowy w Brodnicy" },
  TO1C: { sad: "Sąd Rejonowy w Chełmnie" },
  TO1G: { sad: "Sąd Rejonowy w Golubiu-Dobrzyniu" },
  TO1U: { sad: "Sąd Rejonowy w Grudziądzu" },
  TO1T: { sad: "Sąd Rejonowy w Toruniu" },
  TO1W: { sad: "Sąd Rejonowy w Wąbrzeźnie" },
  WL1A: { sad: "Sąd Rejonowy w Aleksandrowie Kujawskim" },
  WL1L: { sad: "Sąd Rejonowy w Lipnie" },
  WL1R: { sad: "Sąd Rejonowy w Radziejowie" },
  WL1Y: { sad: "Sąd Rejonowy w Rypinie" },
  WL1W: { sad: "Sąd Rejonowy we Włocławku" },
  BB1B: { sad: "Sąd Rejonowy w Bielsku-Białej" },
  BB1C: { sad: "Sąd Rejonowy w Cieszynie" },
  BB1Z: { sad: "Sąd Rejonowy w Żywcu" },
  CZ1C: { sad: "Sąd Rejonowy w Częstochowie" },
  CZ2C: {
    sad: "Sąd Rejonowy w Częstochowie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Kłobucku",
  },
  CZ1L: { sad: "Sąd Rejonowy w Lublińcu" },
  CZ1M: { sad: "Sąd Rejonowy w Myszkowie" },
  CZ1Z: { sad: "Sąd Rejonowy w Zawierciu" },
  GL1G: { sad: "Sąd Rejonowy w Gliwicach" },
  GL1J: { sad: "Sąd Rejonowy w Jastrzębiu-Zdroju" },
  GL1R: { sad: "Sąd Rejonowy w Raciborzu" },
  GL1S: { sad: "Sąd Rejonowy w Rudzie Śląskiej" },
  GL1Y: { sad: "Sąd Rejonowy w Rybniku" },
  GL1T: { sad: "Sąd Rejonowy w Tarnowskich Górach" },
  GL1W: { sad: "Sąd Rejonowy w Wodzisławiu Śląskim" },
  GL1Z: { sad: "Sąd Rejonowy w Zabrzu" },
  GL1X: { sad: "Sąd Rejonowy w Żorach" },
  KA1B: { sad: "Sąd Rejonowy w Będzinie" },
  KA1Y: { sad: "Sąd Rejonowy w Bytomiu" },
  KA1C: { sad: "Sąd Rejonowy w Chorzowie" },
  KA1D: { sad: "Sąd Rejonowy w Dąbrowie Górniczej" },
  KA1J: { sad: "Sąd Rejonowy w Jaworznie" },
  KA1K: { sad: "Sąd Rejonowy Katowice-Wschód w Katowicach" },
  KA1M: { sad: "Sąd Rejonowy w Mikołowie" },
  KA1L: { sad: "Sąd Rejonowy w Mysłowicach" },
  KA1P: { sad: "Sąd Rejonowy w Pszczynie" },
  KA1I: { sad: "Sąd Rejonowy w Siemianowicach Śląskich" },
  KA1S: { sad: "Sąd Rejonowy w Sosnowcu" },
  KA1T: { sad: "Sąd Rejonowy w Tychach" },
  KI1B: { sad: "Sąd Rejonowy w Busku-Zdroju" },
  KI1I: {
    sad: "Sąd Rejonowy w Busku-Zdroju",
    wydzial: "Wydział Zamiejscowy z siedzibą w Kazimierzy Wielkiej",
  },
  KI1J: { sad: "Sąd Rejonowy w Jędrzejowie" },
  KI1L: { sad: "Sąd Rejonowy w Kielcach" },
  KI1K: { sad: "Sąd Rejonowy w Końskich" },
  KI1T: { sad: "Sąd Rejonowy w Opatowie" },
  KI1O: { sad: "Sąd Rejonowy w Ostrowcu Świętokrzyskim" },
  KI1P: { sad: "Sąd Rejonowy w Pińczowie" },
  KI1S: { sad: "Sąd Rejonowy w Sandomierzu" },
  KI1R: { sad: "Sąd Rejonowy w Skarżysku-Kamiennej" },
  KI1H: { sad: "Sąd Rejonowy w Starachowicach" },
  KI1A: { sad: "Sąd Rejonowy w Staszowie" },
  KI1W: { sad: "Sąd Rejonowy we Włoszczowie" },
  KR1C: { sad: "Sąd Rejonowy w Chrzanowie" },
  KR1K: {
    sad: "Sąd Rejonowy dla Krakowa-Krowodrzy w Krakowie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Czernichowie",
  },
  KR2K: {
    sad: "Sąd Rejonowy dla Krakowa-Krowodrzy w Krakowie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Krzeszowicach",
  },
  KR1H: {
    sad: "Sąd Rejonowy dla Krakowa-Nowej Huty w Krakowie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Proszowicach",
  },
  KR1P: { sad: "Sąd Rejonowy dla Krakowa-Podgórza w Krakowie" },
  KR2P: {
    sad: "Sąd Rejonowy dla Krakowa-Podgórza w Krakowie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Skale",
  },
  KR1M: { sad: "Sąd Rejonowy w Miechowie" },
  KR1S: { sad: "Sąd Rejonowy w Miechowie", wydzial: "Wydział Zamiejscowy z siedzibą w Słomnikach" },
  KR1Y: { sad: "Sąd Rejonowy w Myślenicach" },
  KR2Y: {
    sad: "Sąd Rejonowy w Myślenicach",
    wydzial: "Wydział Zamiejscowy z siedzibą w Dobczycach",
  },
  KR1O: { sad: "Sąd Rejonowy w Olkuszu" },
  KR1E: { sad: "Sąd Rejonowy w Oświęcimiu" },
  KR2E: { sad: "Sąd Rejonowy w Oświęcimiu", wydzial: "Wydział Zamiejscowy z siedzibą w Kętach" },
  KR1B: { sad: "Sąd Rejonowy w Suchej Beskidzkiej" },
  KR1W: { sad: "Sąd Rejonowy w Wadowicach" },
  KR1I: { sad: "Sąd Rejonowy w Wieliczce" },
  KR2I: {
    sad: "Sąd Rejonowy w Wieliczce",
    wydzial: "Wydział Zamiejscowy z siedzibą w Niepołomicach",
  },
  KR3I: { sad: "Sąd Rejonowy w Wieliczce", wydzial: "Wydział Zamiejscowy z siedzibą w Skawinie" },
  NS1G: { sad: "Sąd Rejonowy w Gorlicach" },
  NS1L: { sad: "Sąd Rejonowy w Limanowej" },
  NS2L: {
    sad: "Sąd Rejonowy w Limanowej",
    wydzial: "Wydział Zamiejscowy z siedzibą w Mszanie Dolnej",
  },
  NS1S: { sad: "Sąd Rejonowy w Nowym Sączu" },
  NS1M: { sad: "Sąd Rejonowy w Nowym Sączu", wydzial: "Wydział Zamiejscowy z siedzibą w Muszynie" },
  NS1T: { sad: "Sąd Rejonowy w Nowym Targu" },
  NS1Z: { sad: "Sąd Rejonowy w Zakopanem" },
  TR1O: { sad: "Sąd Rejonowy w Bochni" },
  TR1B: { sad: "Sąd Rejonowy w Brzesku" },
  TR1D: { sad: "Sąd Rejonowy w Dąbrowie Tarnowskiej" },
  TR1T: { sad: "Sąd Rejonowy w Tarnowie" },
  TR2T: { sad: "Sąd Rejonowy w Tarnowie", wydzial: "Wydział Zamiejscowy z siedzibą w Tuchowie" },
  LU1B: { sad: "Sąd Rejonowy w Białej Podlaskiej" },
  LU1C: { sad: "Sąd Rejonowy w Chełmie" },
  LU1K: { sad: "Sąd Rejonowy w Kraśniku" },
  LU1A: { sad: "Sąd Rejonowy w Lubartowie" },
  LU1S: { sad: "Sąd Rejonowy Lublin-Wschód w Lublinie z siedzibą w Świdniku" },
  LU1I: { sad: "Sąd Rejonowy Lublin-Zachód w Lublinie" },
  LU1O: { sad: "Sąd Rejonowy w Opolu Lubelskim" },
  LU1P: { sad: "Sąd Rejonowy w Puławach" },
  LU1R: { sad: "Sąd Rejonowy w Radzyniu Podlaskim" },
  LU1Y: { sad: "Sąd Rejonowy w Rykach" },
  LU1W: { sad: "Sąd Rejonowy we Włodawie" },
  RA1G: { sad: "Sąd Rejonowy w Grójcu" },
  RA2G: { sad: "Sąd Rejonowy w Grójcu", wydzial: "Wydział Zamiejscowy z siedzibą w Białobrzegach" },
  RA1K: { sad: "Sąd Rejonowy w Kozienicach" },
  RA1L: { sad: "Sąd Rejonowy w Lipsku" },
  RA1P: { sad: "Sąd Rejonowy w Przysusze" },
  RA1R: { sad: "Sąd Rejonowy w Radomiu" },
  RA1S: { sad: "Sąd Rejonowy w Szydłowcu" },
  RA1Z: { sad: "Sąd Rejonowy w Zwoleniu" },
  SI1G: { sad: "Sąd Rejonowy w Garwolinie" },
  LU1U: { sad: "Sąd Rejonowy w Łukowie" },
  SI1M: { sad: "Sąd Rejonowy w Mińsku Mazowieckim" },
  SI1S: { sad: "Sąd Rejonowy w Siedlcach" },
  SI2S: { sad: "Sąd Rejonowy w Siedlcach", wydzial: "Wydział Zamiejscowy z siedzibą w Łosicach" },
  SI1P: { sad: "Sąd Rejonowy w Sokołowie Podlaskim" },
  SI1W: { sad: "Sąd Rejonowy w Węgrowie" },
  ZA1B: { sad: "Sąd Rejonowy w Biłgoraju" },
  ZA1H: { sad: "Sąd Rejonowy w Hrubieszowie" },
  ZA1J: { sad: "Sąd Rejonowy w Janowie Lubelskim" },
  ZA1K: { sad: "Sąd Rejonowy w Krasnymstawie" },
  ZA1T: { sad: "Sąd Rejonowy w Tomaszowie Lubelskim" },
  ZA1Z: { sad: "Sąd Rejonowy w Zamościu" },
  KZ1J: { sad: "Sąd Rejonowy w Jarocinie" },
  KZ1A: { sad: "Sąd Rejonowy w Kaliszu" },
  KZ1E: { sad: "Sąd Rejonowy w Kępnie" },
  KZ1R: { sad: "Sąd Rejonowy w Krotoszynie" },
  KZ1W: { sad: "Sąd Rejonowy w Ostrowie Wielkopolskim" },
  KZ1O: { sad: "Sąd Rejonowy w Ostrzeszowie" },
  KZ1P: { sad: "Sąd Rejonowy w Pleszewie" },
  LD1B: { sad: "Sąd Rejonowy w Brzezinach" },
  LD1K: { sad: "Sąd Rejonowy w Kutnie" },
  LD1Y: { sad: "Sąd Rejonowy w Łęczycy" },
  LD1M: { sad: "Sąd Rejonowy dla Łodzi-Śródmieścia w Łodzi" },
  LD1O: { sad: "Sąd Rejonowy w Łowiczu" },
  LD1P: { sad: "Sąd Rejonowy w Pabianicach" },
  LD1R: { sad: "Sąd Rejonowy w Rawie Mazowieckiej" },
  LD1H: { sad: "Sąd Rejonowy w Skierniewicach" },
  LD1G: { sad: "Sąd Rejonowy w Zgierzu" },
  PT1B: { sad: "Sąd Rejonowy w Bełchatowie" },
  PT1O: { sad: "Sąd Rejonowy w Opocznie" },
  PT1P: { sad: "Sąd Rejonowy w Piotrkowie Trybunalskim" },
  PT1R: { sad: "Sąd Rejonowy w Radomsku" },
  PT1T: { sad: "Sąd Rejonowy w Tomaszowie Mazowieckim" },
  PL1C: { sad: "Sąd Rejonowy w Ciechanowie" },
  PL1G: { sad: "Sąd Rejonowy w Gostyninie" },
  PL1M: { sad: "Sąd Rejonowy w Mławie" },
  PL2M: { sad: "Sąd Rejonowy w Mławie", wydzial: "Wydział Zamiejscowy z siedzibą w Żurominie" },
  PL1P: { sad: "Sąd Rejonowy w Płocku" },
  PL1L: { sad: "Sąd Rejonowy w Płońsku" },
  PL1E: { sad: "Sąd Rejonowy w Sierpcu" },
  PL1O: { sad: "Sąd Rejonowy w Sochaczewie" },
  PL1Z: { sad: "Sąd Rejonowy w Żyrardowie" },
  SR1L: { sad: "Sąd Rejonowy w Łasku" },
  SR2L: { sad: "Sąd Rejonowy w Łasku", wydzial: "Wydział Zamiejscowy z siedzibą w Poddębicach" },
  SR1S: { sad: "Sąd Rejonowy w Sieradzu" },
  SR1W: { sad: "Sąd Rejonowy w Wieluniu" },
  SR2W: { sad: "Sąd Rejonowy w Wieluniu", wydzial: "Wydział Zamiejscowy z siedzibą w Pajęcznie" },
  SR1Z: { sad: "Sąd Rejonowy w Zduńskiej Woli" },
  KN1K: { sad: "Sąd Rejonowy w Kole" },
  KN1N: { sad: "Sąd Rejonowy w Koninie" },
  KN1S: { sad: "Sąd Rejonowy w Słupcy" },
  KN1T: { sad: "Sąd Rejonowy w Turku" },
  PO1H: { sad: "Sąd Rejonowy w Chodzieży" },
  PO2H: { sad: "Sąd Rejonowy w Chodzieży", wydzial: "Wydział Zamiejscowy z siedzibą w Wyrzysku" },
  PO1G: { sad: "Sąd Rejonowy w Gnieźnie" },
  PO1Y: { sad: "Sąd Rejonowy w Gostyniu" },
  PO1S: { sad: "Sąd Rejonowy w Grodzisku Wielkopolskim" },
  PO1K: { sad: "Sąd Rejonowy w Kościanie" },
  PO1L: { sad: "Sąd Rejonowy w Lesznie" },
  PO1N: { sad: "Sąd Rejonowy w Nowym Tomyślu" },
  PO1O: { sad: "Sąd Rejonowy w Obornikach" },
  PO1I: { sad: "Sąd Rejonowy w Pile" },
  PO1P: {
    sad: "Sąd Rejonowy Poznań-Stare Miasto w Poznaniu",
    zakres:
      "dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Grunwald, Jeżyce i Stare Miasto oraz gmin: Czerwonak, Dopiewo, Murowana Goślina, Suchy Las i Tarnowo Podgórne",
  },
  PO2P: {
    sad: "Sąd Rejonowy Poznań-Stare Miasto w Poznaniu",
    zakres:
      "dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Nowe Miasto i Wilda, miast Luboń i Puszczykowo oraz gmin Komorniki i Swarzędz",
  },
  PO1R: { sad: "Sąd Rejonowy w Rawiczu" },
  PO1A: { sad: "Sąd Rejonowy w Szamotułach" },
  PO2A: {
    sad: "Sąd Rejonowy w Szamotułach",
    wydzial: "Wydział Zamiejscowy z siedzibą w Międzychodzie",
  },
  PO1M: { sad: "Sąd Rejonowy w Śremie" },
  PO1D: { sad: "Sąd Rejonowy w Środzie Wielkopolskiej" },
  PO1T: { sad: "Sąd Rejonowy w Trzciance" },
  PO2T: { sad: "Sąd Rejonowy w Trzciance", wydzial: "Wydział Zamiejscowy z siedzibą w Czarnkowie" },
  PO1B: { sad: "Sąd Rejonowy w Wągrowcu" },
  PO1E: { sad: "Sąd Rejonowy w Wolsztynie" },
  PO1F: { sad: "Sąd Rejonowy we Wrześni" },
  PO1Z: { sad: "Sąd Rejonowy w Złotowie" },
  ZG1K: { sad: "Sąd Rejonowy w Krośnie Odrzańskim" },
  ZG2K: {
    sad: "Sąd Rejonowy w Krośnie Odrzańskim",
    wydzial: "Wydział Zamiejscowy z siedzibą w Gubinie",
  },
  ZG1N: { sad: "Sąd Rejonowy w Nowej Soli" },
  ZG1S: { sad: "Sąd Rejonowy w Świebodzinie" },
  ZG2S: {
    sad: "Sąd Rejonowy w Świebodzinie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Sulechowie",
  },
  ZG1W: { sad: "Sąd Rejonowy we Wschowie" },
  ZG1E: { sad: "Sąd Rejonowy w Zielonej Górze" },
  ZG1G: { sad: "Sąd Rejonowy w Żaganiu" },
  ZG1R: { sad: "Sąd Rejonowy w Żarach" },
  KS1B: { sad: "Sąd Rejonowy w Brzozowie" },
  KS1J: { sad: "Sąd Rejonowy w Jaśle" },
  KS1K: { sad: "Sąd Rejonowy w Krośnie" },
  KS1E: { sad: "Sąd Rejonowy w Lesku" },
  KS2E: {
    sad: "Sąd Rejonowy w Lesku",
    wydzial: "Wydział Zamiejscowy z siedzibą w Ustrzykach Dolnych",
  },
  KS1S: { sad: "Sąd Rejonowy w Sanoku" },
  PR1J: { sad: "Sąd Rejonowy w Jarosławiu" },
  PR1L: { sad: "Sąd Rejonowy w Lubaczowie" },
  PR1P: { sad: "Sąd Rejonowy w Przemyślu" },
  PR1R: { sad: "Sąd Rejonowy w Przeworsku" },
  PR2R: { sad: "Sąd Rejonowy w Przeworsku", wydzial: "Wydział Zamiejscowy z siedzibą w Sieniawie" },
  RZ1D: { sad: "Sąd Rejonowy w Dębicy" },
  RZ1E: { sad: "Sąd Rejonowy w Leżajsku" },
  RZ1A: { sad: "Sąd Rejonowy w Łańcucie" },
  RZ1R: { sad: "Sąd Rejonowy w Ropczycach" },
  RZ1Z: { sad: "Sąd Rejonowy w Rzeszowie" },
  RZ2Z: { sad: "Sąd Rejonowy w Rzeszowie", wydzial: "Wydział Zamiejscowy z siedzibą w Tyczynie" },
  RZ1S: { sad: "Sąd Rejonowy w Strzyżowie" },
  TB1K: { sad: "Sąd Rejonowy w Kolbuszowej" },
  TB1M: { sad: "Sąd Rejonowy w Mielcu" },
  TB1N: { sad: "Sąd Rejonowy w Nisku" },
  TB1S: { sad: "Sąd Rejonowy w Stalowej Woli" },
  TB1T: { sad: "Sąd Rejonowy w Tarnobrzegu" },
  GW1G: { sad: "Sąd Rejonowy w Gorzowie Wielkopolskim" },
  GW1M: { sad: "Sąd Rejonowy w Międzyrzeczu" },
  GW1S: { sad: "Sąd Rejonowy w Słubicach" },
  GW1K: { sad: "Sąd Rejonowy w Strzelcach Krajeńskich" },
  GW1U: { sad: "Sąd Rejonowy w Sulęcinie" },
  KO1B: { sad: "Sąd Rejonowy w Białogardzie" },
  KO2B: {
    sad: "Sąd Rejonowy w Białogardzie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Świdwinie",
  },
  KO1D: { sad: "Sąd Rejonowy w Drawsku Pomorskim" },
  KO1L: { sad: "Sąd Rejonowy w Kołobrzegu" },
  KO1K: { sad: "Sąd Rejonowy w Koszalinie" },
  KO1E: { sad: "Sąd Rejonowy w Sławnie" },
  KO1I: { sad: "Sąd Rejonowy w Szczecinku" },
  KO1W: { sad: "Sąd Rejonowy w Wałczu" },
  SZ1C: { sad: "Sąd Rejonowy w Choszcznie" },
  SZ1O: { sad: "Sąd Rejonowy w Goleniowie" },
  SZ1G: { sad: "Sąd Rejonowy w Gryficach" },
  SZ1K: { sad: "Sąd Rejonowy w Kamieniu Pomorskim" },
  SZ1L: { sad: "Sąd Rejonowy w Łobzie" },
  SZ1Y: { sad: "Sąd Rejonowy w Gryfinie" },
  SZ1M: { sad: "Sąd Rejonowy w Myśliborzu" },
  SZ1T: { sad: "Sąd Rejonowy w Stargardzie" },
  SZ2T: {
    sad: "Sąd Rejonowy w Stargardzie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Pyrzycach",
  },
  SZ1S: { sad: "Sąd Rejonowy Szczecin-Prawobrzeże i Zachód w Szczecinie" },
  SZ2S: {
    sad: "Sąd Rejonowy Szczecin-Prawobrzeże i Zachód w Szczecinie",
    wydzial: "Wydział Zamiejscowy z siedzibą w Policach",
  },
  SZ1W: { sad: "Sąd Rejonowy w Świnoujściu" },
  WA1G: { sad: "Sąd Rejonowy w Grodzisku Mazowieckim" },
  WA1I: { sad: "Sąd Rejonowy w Piasecznie" },
  WA1P: { sad: "Sąd Rejonowy w Pruszkowie" },
  WA1M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Bemowo, Bielany, Ochota i Żoliborz oraz gminy Izabelin",
  },
  WA2M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Mokotów i Wilanów",
  },
  WA3M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Białołęka, Praga-Północ, Targówek",
  },
  WA4M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic Śródmieście i Wola oraz gminy Łomianki",
  },
  WA5M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Ursus, Ursynów i Włochy",
  },
  WA6M: {
    sad: "Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie",
    zakres:
      "dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Praga-Południe, Rembertów, Wawer i Wesoła",
  },
  WA1L: { sad: "Sąd Rejonowy Sąd Okręgowy Warszawa-Praga w Warszawie WP w Legionowie" },
  WA1N: { sad: "Sąd Rejonowy w Nowym Dworze Mazowieckim" },
  WA1O: { sad: "Sąd Rejonowy w Otwocku" },
  WA1W: { sad: "Sąd Rejonowy w Wołominie" },
  JG1B: { sad: "Sąd Rejonowy w Bolesławcu" },
  JG1J: { sad: "Sąd Rejonowy w Jeleniej Górze" },
  JG1K: { sad: "Sąd Rejonowy w Kamiennej Górze" },
  JG1L: { sad: "Sąd Rejonowy w Lubaniu" },
  JG1S: { sad: "Sąd Rejonowy w Lwówku Śląskim" },
  JG1Z: { sad: "Sąd Rejonowy w Zgorzelcu" },
  LE1G: { sad: "Sąd Rejonowy w Głogowie" },
  LE1J: { sad: "Sąd Rejonowy w Jaworze" },
  LE1L: { sad: "Sąd Rejonowy w Legnicy" },
  LE1U: { sad: "Sąd Rejonowy w Lubinie" },
  LE1Z: { sad: "Sąd Rejonowy w Złotoryi" },
  OP1B: { sad: "Sąd Rejonowy w Brzegu" },
  OP1G: { sad: "Sąd Rejonowy w Głubczycach" },
  OP1K: { sad: "Sąd Rejonowy w Kędzierzynie-Koźlu" },
  OP1U: { sad: "Sąd Rejonowy w Kluczborku" },
  OP1N: { sad: "Sąd Rejonowy w Nysie" },
  OP1L: { sad: "Sąd Rejonowy w Oleśnie" },
  OP1O: { sad: "Sąd Rejonowy w Opolu" },
  OP1P: { sad: "Sąd Rejonowy w Prudniku" },
  OP1S: { sad: "Sąd Rejonowy w Strzelcach Opolskich" },
  SW1D: { sad: "Sąd Rejonowy w Dzierżoniowie" },
  SW1K: { sad: "Sąd Rejonowy w Kłodzku" },
  SW1S: { sad: "Sąd Rejonowy w Świdnicy" },
  SW1W: { sad: "Sąd Rejonowy w Wałbrzychu" },
  SW1Z: { sad: "Sąd Rejonowy w Ząbkowicach Śląskich" },
  WR1M: { sad: "Sąd Rejonowy w Miliczu" },
  WR1E: { sad: "Sąd Rejonowy w Oleśnicy" },
  WR1O: { sad: "Sąd Rejonowy w Oławie" },
  WR1T: { sad: "Sąd Rejonowy w Strzelinie" },
  WR1S: { sad: "Sąd Rejonowy w Środzie Śląskiej" },
  WR1W: { sad: "Sąd Rejonowy w Trzebnicy" },
  WR1L: { sad: "Sąd Rejonowy w Wołowie" },
};

/** Kod wydziału (4 znaki) z numeru KW w dowolnym zapisie, np. "SL1S/00061444/8" → "SL1S". */
export function kodWydzialuKw(nrKw: string | null | undefined): string | null {
  const m = /^\s*([A-Z]{2}\d[A-Z])/i.exec(String(nrKw ?? ""));
  return m ? m[1].toUpperCase() : null;
}

/**
 * Pełna nazwa sądu prowadzącego księgę — z kodu wydziału w numerze KW.
 * Wydział zamiejscowy jest dopisany po przecinku. `null`, gdy kodu nie ma w wykazie.
 */
export function sadZKodu(nrKw: string | null | undefined): string | null {
  const kod = kodWydzialuKw(nrKw);
  const w = kod ? KW_COURT_CODES[kod] : undefined;
  if (!w) return null;
  return w.wydzial ? `${w.sad}, ${w.wydzial}` : w.sad;
}
