-- =====================================================================================
-- RUNBOOK: synchronizacja danych produkcja (Lovable) -> nowa baza (Supabase vkzndnaoxhdxrxlpntcb)
-- Dokładnie te kroki wykonano przy próbnej kopii 2026-10-10 (wynik: 245/245 tabel zgodnych).
-- Przy finalnej kopii (okno serwisowe) powtórzyć w tej kolejności. Oznaczenia:
--   [NOWA]  — konektor Supabase, rola postgres, limit 2 min/wywołanie
--   [STARA] — narzędzie Lovable query_database, rola postgres
-- Założenia: schemat nowej bazy = produkcja (schema-diff.sql bez różnic poza rls_auto_enable),
-- postgres_fdw/server newdb/user mapping/_mig_remote istnieją w starej bazie (patrz sekcja 0),
-- rola migrator i schemat _mig (staging auth_users/auth_identities, ddl, ddl_log, run2) w nowej.
-- Konektor Supabase wymaga potwierdzenia dla drop/delete/truncate — zaplanować obecność właściciela.
-- =====================================================================================

-- ===== 0. [STARA] FDW — tylko jeśli nie istnieje lub schemat się zmienił (import foreign schema jest migawką) =====
-- create extension if not exists postgres_fdw with schema extensions;
-- create server if not exists newdb foreign data wrapper postgres_fdw
--   options (host 'db.vkzndnaoxhdxrxlpntcb.supabase.co', port '5432', dbname 'postgres', sslmode 'require', batch_size '1000');
-- create user mapping if not exists for postgres server newdb options (user 'migrator', password '<hasło migratora>');
-- drop schema if exists _mig_remote cascade;  create schema _mig_remote;
-- import foreign schema public from server newdb into _mig_remote;
-- import foreign schema drizzle from server newdb into _mig_remote;
-- import foreign schema supabase_migrations from server newdb into _mig_remote;
-- import foreign schema _mig limit to (auth_users, auth_identities) from server newdb into _mig_remote;

-- ===== 1. [NOWA] Przygotowanie (odwracalne) =====
alter role migrator bypassrls;
grant usage on schema public, drizzle, supabase_migrations to migrator;
grant select, insert, update, delete, truncate on all tables in schema public to migrator;
grant select, insert, update, delete, truncate on all tables in schema drizzle to migrator;
grant select, insert, update, delete, truncate on all tables in schema supabase_migrations to migrator;
grant usage, select, update on all sequences in schema public to migrator;
grant usage, select, update on all sequences in schema drizzle to migrator;
do $$ declare r record; begin
  for r in select n.nspname, c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname in ('public','drizzle','supabase_migrations') and c.relkind = 'r' loop
    execute format('alter table %I.%I disable trigger user', r.nspname, r.relname);
  end loop;
  for r in select c.relname, a.attname from pg_attribute a join pg_class c on c.oid = a.attrelid
           where c.relnamespace = 'public'::regnamespace and a.attidentity = 'a' and not a.attisdropped loop
    execute format('alter table public.%I alter column %I set generated by default', r.relname, r.attname);
  end loop;
  for r in select c.conname, r1.relname as child from pg_constraint c join pg_class r1 on r1.oid = c.conrelid join pg_class r2 on r2.oid = c.confrelid
           where c.contype = 'f' and r1.relnamespace = 'public'::regnamespace
             and r1.relname in ('ai_seo_articles','ai_seo_topics') and r2.relname in ('ai_seo_articles','ai_seo_topics') loop
    execute format('alter table public.%I alter constraint %I deferrable initially deferred', r.child, r.conname);
  end loop;
end $$;
-- trigger on_auth_user_created na auth.users nie da się wyłączyć (brak własności) -> neutralizacja funkcji:
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path to 'public' as $$ begin return new; end $$;
update _mig.ddl_log set ok = false, err = 'reset: przywrócić oryginał po załadowaniu auth.users'
where seq = (select seq from _mig.ddl where phase = 7 and obj = 'handle_new_user()');

-- ===== 1b. [NOWA] Finalna kopia: opróżnienie celu (potwierdzenie w konektorze) =====
-- do $$ declare r record; begin
--   for r in select n.nspname, c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
--            where n.nspname in ('public','drizzle','supabase_migrations') and c.relkind = 'r' loop
--     execute format('truncate table %I.%I cascade', r.nspname, r.relname);
--   end loop;
-- end $$;
-- truncate table _mig.auth_users, _mig.auth_identities;
-- delete from auth.identities; delete from auth.users;   -- postgres ma delete na auth.*

-- ===== 2. [STARA] Staging auth =====
insert into _mig_remote.auth_users select * from auth.users;
insert into _mig_remote.auth_identities select * from auth.identities;

-- ===== 3. [NOWA] auth.users / auth.identities ze stagingu (bez kolumn generated, np. confirmed_at) =====
do $$ declare cols text; begin
  select string_agg(quote_ident(attname), ', ' order by attnum) into cols
  from pg_attribute where attrelid = 'auth.users'::regclass and attnum > 0 and not attisdropped and attgenerated = '';
  execute format('insert into auth.users (%s) select %s from _mig.auth_users', cols, cols);
  select string_agg(quote_ident(attname), ', ' order by attnum) into cols
  from pg_attribute where attrelid = 'auth.identities'::regclass and attnum > 0 and not attisdropped and attgenerated = '';
  execute format('insert into auth.identities (%s) select %s from _mig.auth_identities', cols, cols);
end $$;

-- ===== 4. [STARA] Tabele w kolejności topologicznej FK (poziomy; w poziomie kolejność dowolna) =====
-- Szablon jednego wywołania (jedna transakcja; błąd cofa całość). Listę tabel podstawiać z poziomów poniżej.
-- create temp table _res(t text, n bigint, ms int);
-- do $$
-- declare item text; sch text; tb text; cols text; n bigint; t0 timestamptz; filt text;
-- begin
--   foreach item in array array[ ...LISTA... ] loop
--     sch := split_part(item, '.', 1); tb := split_part(item, '.', 2);
--     select string_agg(quote_ident(a.attname), ', ' order by a.attnum) into cols
--     from pg_attribute a where a.attrelid = format('%I.%I', sch, tb)::regclass and a.attnum > 0 and not a.attisdropped and a.attgenerated = '';
--     filt := case when tb = 'lead_communications' then ' where lead_id is distinct from ''8e20abbc-48f9-4df4-be2f-fdf04f2db0de''' else '' end;
--     t0 := clock_timestamp();
--     execute format('insert into _mig_remote.%I (%s) select %s from %I.%I%s', tb, cols, cols, sch, tb, filt);
--     get diagnostics n = row_count;
--     insert into _res values (item, n, (extract(epoch from clock_timestamp() - t0) * 1000)::int);
--   end loop;
-- end $$;
-- select json_build_object('tables', count(*), 'rows', sum(n), 'total_ms', sum(ms)) from _res;
--
-- Poziom 0 (138; rodzic zewnętrzny tylko auth.users):
--   drizzle.__drizzle_migrations, supabase_migrations.schema_migrations, public.access_audit_logs,
--   access_expiry_notifications, access_products, access_webhook_logs, accounting_entities, affiliate_audit_logs,
--   affiliate_commission_rules, affiliate_partners, affiliate_payout_batches, affiliate_unregistered_activity_limits,
--   ai_admin_audit_log, ai_admin_conversations, ai_admin_settings, ai_competitors, ai_funnel_events, ai_funnel_insights,
--   ai_growth_action_log, ai_growth_settings, ai_landings, ai_linkbuilding_suggestions, ai_outreach_targets,
--   ai_serp_keywords, aml_audit_log, aml_certificates, aml_customers, aml_settings, audit_logs, auto_distribution_settings,
--   avatar_faqs, change_requests, client_lead_forwards, clients, consent_documents, consumer_withdrawals,
--   cookie_consent_log, coowner_registry_checks, crbr_cache, didit_verifications, dilisense_cache, document_templates,
--   email_segments, email_send_log, email_send_state, email_subscribers, email_templates, email_unsubscribe_tokens,
--   esign_envelopes, external_api_logs, fakturowo_documents, flood_risk_cache, geo_unit_adjacency,
--   geo_unit_location_metrics, geo_units, google_ad_drafts, gus_bdl_cache, institution_mail_agent_settings,
--   integration_settings, investment_projects, investment_risk_assessments, investor_assistant_messages,
--   investor_kw_checks, investor_orders, investor_screenings, krs_cache, kw_analysis, kw_documents, kw_fetch_attempts,
--   kw_fetch_jobs, kw_jurisdiction_versions, kw_number_range_statistics, kw_owners_business_check, kw_quota_state,
--   kw_section_sources, landing_pages, lead_magnets, legal_deliveries, legal_documents, loan_reminder_email_variants,
--   location_scoring_import_jobs, location_scoring_model_versions, location_scoring_settings, marketing_campaigns,
--   marketing_materials, meta_ad_accounts, meta_lead_forms, meta_sync_log, nbp_real_estate_cache, nda_accessions,
--   operator_invites, pep_position_catalog, pep_reference_persons, population_grid_metrics, project_document_access_log,
--   project_module_acceptances, project_module_access, project_module_applications, project_module_audit_log,
--   project_module_screenings, project_module_settings, property_analyses, property_analysis_logs,
--   property_document_extractions, property_location_analysis_cache, push_subscriptions, rcn_cache,
--   reminder_email_schedule, representation_web_enrichment_cache, sanctions_reference_entries, screening_audit_log,
--   screening_name_index, screening_queue, screening_settings, screening_source_imports, short_links, social_posts,
--   social_publish_queue, storage_migration_log, studio_broll_assets, studio_default_avatars, studio_images,
--   studio_settings, studio_video_jobs, suppressed_emails, text_agent_knowledge, text_agent_settings,
--   tiktok_integration, tpay_transaction_buyers, tracking_settings, training_videos, user_roles, video_renditions,
--   voicebot_settings, wind_borrowers, x_integration, youtube_integration, youtube_publish_queue
-- Poziom 1 (36): accounting_documents, accounting_sync_status, affiliate_commission_events, affiliate_invoices,
--   affiliate_network_closure, ai_admin_memory, ai_admin_messages, ai_backlinks, ai_competitor_snapshots,
--   ai_landing_variants, ai_outreach_messages, ai_serp_rankings, aml_risk_assessments, aml_screenings, aml_transactions,
--   campaign_clicks, consent_acceptances, email_campaigns, esign_signers, investment_project_versions,
--   investor_agreement_acceptances, investor_order_matches, investors, kw_court_departments, landing_leads,
--   lead_attributions, lead_magnet_posts, lead_magnet_signups, loan_applications, meta_ad_drafts, meta_campaigns,
--   profiles, project_assignments, property_type_location_weights, sales_invoices, wind_loans
-- Poziom 2 (40): access_payments, affiliate_commissions, ai_landing_events, ai_landing_optimizations,
--   aml_threshold_entries, analysis_pipeline_runs, auto_distribution_proposals, automation_events, broker_settlements,
--   call_queue, chat_threads, client_profiles, contact_events, email_campaign_recipients, esign_events,
--   individual_sales_register, institution_qa_threads, institutional_investor_settings, investor_distribution_criteria,
--   investor_offers, investor_order_events, investor_success_fees, kw_jurisdiction_areas, kw_land_register_analyses,
--   kw_location_observations, lead_magnet_triggers, loan_proposals, loan_reminder_email_sends, loan_status_history,
--   location_scoring_results, meta_leads, missing_info_follow_ups, offer_distributions, pep_declarations,
--   project_assignment_notifications, project_info_requests, project_proposals, properties, screening_subjects,
--   wind_collection_cases
-- Poziom 3 (13): access_entitlements, affiliate_payout_items, aml_cases, chat_messages, documents,
--   investor_opportunity_unlocks, kw_finding_resolutions, leads, missing_info_follow_up_sends,
--   offer_distribution_messages, screening_runs, screening_subject_status, wind_events
-- Poziom 4 (11): aml_case_transactions, aml_reports, criteria_change_proposals, generated_documents,
--   institution_mail_intel, lead_communications (z filtrem), lead_follow_up_schedule, messenger_outbox,
--   meta_capi_events, screening_cases, wind_documents
-- Poziom 5 (5): aml_attachments, aml_report_versions, aml_submission_queue, screening_false_positives, screening_hits
-- Cykl (jedna transakcja, FK odroczone): ai_seo_topics, ai_seo_articles
-- Uwaga: przy zmianie schematu przeliczyć poziomy (zapytanie z tabelami tymczasowymi fk_edges/tbl — patrz
-- docs/migracja-z-lovable.md, krok 6) i sprawdzić, czy pojawiły się nowe cykle.

-- ===== 5. [STARA] Pozycje sekwencji -> _mig.ddl (faza 16) =====
-- generator fazy 16 z ddl-generators.sql opakowany w szablon TRANSFER (upsert).

-- ===== 6. [NOWA] Przywrócenie =====
do $$ declare r record; begin
  for r in select c.relname, a.attname from pg_attribute a join pg_class c on c.oid = a.attrelid
           where c.relnamespace = 'public'::regnamespace and a.attidentity = 'd' and not a.attisdropped loop
    execute format('alter table public.%I alter column %I set generated always', r.relname, r.attname);
  end loop;
  for r in select n.nspname, c.relname from pg_class c join pg_namespace n on n.oid = c.relnamespace
           where n.nspname in ('public','drizzle','supabase_migrations') and c.relkind = 'r' loop
    execute format('alter table %I.%I enable trigger user', r.nspname, r.relname);
  end loop;
  for r in select r1.relname as child, c.conname from pg_constraint c join pg_class r1 on r1.oid = c.conrelid
           where c.contype = 'f' and c.condeferrable and r1.relnamespace = 'public'::regnamespace loop
    execute format('alter table public.%I alter constraint %I not deferrable', r.child, r.conname);
  end loop;
end $$;
select * from _mig.run2(7, 7, 10);    -- oryginalne handle_new_user
select * from _mig.run2(16, 16, 50);  -- setval
alter role migrator nobypassrls;
revoke all on all tables in schema public from migrator;
revoke all on all tables in schema drizzle from migrator;
revoke all on all tables in schema supabase_migrations from migrator;
revoke all on all sequences in schema public from migrator;
revoke all on all sequences in schema drizzle from migrator;
revoke usage on schema public, drizzle, supabase_migrations from migrator;
-- (po potwierdzeniu) truncate table _mig.auth_users, _mig.auth_identities;  -- hashe haseł nie mają zostać w stagingu

-- ===== 7. Weryfikacja =====
-- [NOWA] stan: identity 'a' = 7, triggery 'O' = 145, FK = 198, deferrable = 0, md5(handle_new_user) = _mig.ddl,
--   count(*) from _mig.ddl_log where not ok = 0, count(*) filter (where active) from cron.job = 0
-- [STARA] liczby wierszy (lokalnie vs _mig_remote.*) — jedyna oczekiwana różnica: lead_communications
-- [STARA] sumy kontrolne: ten sam SQL po obu stronach (dblink 'newdb' z identycznymi set timezone/datestyle/
--   extra_float_digits): select md5(string_agg(md5(t::text), ',' order by <PK>)) from <tabela> t
--   -> oczekiwane 245/245 równych, gdy produkcja jest zatrzymana.
