/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RejestracjaRouteImport } from './routes/rejestracja'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as KlientRouteImport } from './routes/klient'
import { Route as InwestorRouteImport } from './routes/inwestor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlientIndexRouteImport } from './routes/klient.index'
import { Route as InwestorIndexRouteImport } from './routes/inwestor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWnioskiRouteImport } from './routes/admin.wnioski'
import { Route as AdminUstawieniaRouteImport } from './routes/admin.ustawienia'
import { Route as AdminRoleRouteImport } from './routes/admin.role'
import { Route as AdminNieruchomosciRouteImport } from './routes/admin.nieruchomosci'
import { Route as AdminLeadyRouteImport } from './routes/admin.leady'
import { Route as AdminKlienciRouteImport } from './routes/admin.klienci'
import { Route as AdminFollowUpRouteImport } from './routes/admin.follow-up'
import { Route as AdminDokumentyRouteImport } from './routes/admin.dokumenty'
import { Route as AdminWnioskiIdRouteImport } from './routes/admin.wnioski.$id'

const RejestracjaRoute = RejestracjaRouteImport.update({
  id: '/rejestracja',
  path: '/rejestracja',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientRoute = KlientRouteImport.update({
  id: '/klient',
  path: '/klient',
  getParentRoute: () => rootRouteImport,
} as any)
const InwestorRoute = InwestorRouteImport.update({
  id: '/inwestor',
  path: '/inwestor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientIndexRoute = KlientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KlientRoute,
} as any)
const InwestorIndexRoute = InwestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InwestorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWnioskiRoute = AdminWnioskiRouteImport.update({
  id: '/wnioski',
  path: '/wnioski',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUstawieniaRoute = AdminUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoleRoute = AdminRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNieruchomosciRoute = AdminNieruchomosciRouteImport.update({
  id: '/nieruchomosci',
  path: '/nieruchomosci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadyRoute = AdminLeadyRouteImport.update({
  id: '/leady',
  path: '/leady',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKlienciRoute = AdminKlienciRouteImport.update({
  id: '/klienci',
  path: '/klienci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowUpRoute = AdminFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDokumentyRoute = AdminDokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWnioskiIdRoute = AdminWnioskiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWnioskiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inwestor': typeof InwestorRouteWithChildren
  '/klient': typeof KlientRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/nieruchomosci': typeof AdminNieruchomosciRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/inwestor/': typeof InwestorIndexRoute
  '/klient/': typeof KlientIndexRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/nieruchomosci': typeof AdminNieruchomosciRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/inwestor': typeof InwestorIndexRoute
  '/klient': typeof KlientIndexRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inwestor': typeof InwestorRouteWithChildren
  '/klient': typeof KlientRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/nieruchomosci': typeof AdminNieruchomosciRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/inwestor/': typeof InwestorIndexRoute
  '/klient/': typeof KlientIndexRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/logowanie'
    | '/rejestracja'
    | '/admin/dokumenty'
    | '/admin/follow-up'
    | '/admin/klienci'
    | '/admin/leady'
    | '/admin/nieruchomosci'
    | '/admin/role'
    | '/admin/ustawienia'
    | '/admin/wnioski'
    | '/admin/'
    | '/inwestor/'
    | '/klient/'
    | '/admin/wnioski/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logowanie'
    | '/rejestracja'
    | '/admin/dokumenty'
    | '/admin/follow-up'
    | '/admin/klienci'
    | '/admin/leady'
    | '/admin/nieruchomosci'
    | '/admin/role'
    | '/admin/ustawienia'
    | '/admin/wnioski'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/admin/wnioski/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/logowanie'
    | '/rejestracja'
    | '/admin/dokumenty'
    | '/admin/follow-up'
    | '/admin/klienci'
    | '/admin/leady'
    | '/admin/nieruchomosci'
    | '/admin/role'
    | '/admin/ustawienia'
    | '/admin/wnioski'
    | '/admin/'
    | '/inwestor/'
    | '/klient/'
    | '/admin/wnioski/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InwestorRoute: typeof InwestorRouteWithChildren
  KlientRoute: typeof KlientRouteWithChildren
  LogowanieRoute: typeof LogowanieRoute
  RejestracjaRoute: typeof RejestracjaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rejestracja': {
      id: '/rejestracja'
      path: '/rejestracja'
      fullPath: '/rejestracja'
      preLoaderRoute: typeof RejestracjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient': {
      id: '/klient'
      path: '/klient'
      fullPath: '/klient'
      preLoaderRoute: typeof KlientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inwestor': {
      id: '/inwestor'
      path: '/inwestor'
      fullPath: '/inwestor'
      preLoaderRoute: typeof InwestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient/': {
      id: '/klient/'
      path: '/'
      fullPath: '/klient/'
      preLoaderRoute: typeof KlientIndexRouteImport
      parentRoute: typeof KlientRoute
    }
    '/inwestor/': {
      id: '/inwestor/'
      path: '/'
      fullPath: '/inwestor/'
      preLoaderRoute: typeof InwestorIndexRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wnioski': {
      id: '/admin/wnioski'
      path: '/wnioski'
      fullPath: '/admin/wnioski'
      preLoaderRoute: typeof AdminWnioskiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ustawienia': {
      id: '/admin/ustawienia'
      path: '/ustawienia'
      fullPath: '/admin/ustawienia'
      preLoaderRoute: typeof AdminUstawieniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/role': {
      id: '/admin/role'
      path: '/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof AdminRoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nieruchomosci': {
      id: '/admin/nieruchomosci'
      path: '/nieruchomosci'
      fullPath: '/admin/nieruchomosci'
      preLoaderRoute: typeof AdminNieruchomosciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leady': {
      id: '/admin/leady'
      path: '/leady'
      fullPath: '/admin/leady'
      preLoaderRoute: typeof AdminLeadyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/klienci': {
      id: '/admin/klienci'
      path: '/klienci'
      fullPath: '/admin/klienci'
      preLoaderRoute: typeof AdminKlienciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/follow-up': {
      id: '/admin/follow-up'
      path: '/follow-up'
      fullPath: '/admin/follow-up'
      preLoaderRoute: typeof AdminFollowUpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dokumenty': {
      id: '/admin/dokumenty'
      path: '/dokumenty'
      fullPath: '/admin/dokumenty'
      preLoaderRoute: typeof AdminDokumentyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wnioski/$id': {
      id: '/admin/wnioski/$id'
      path: '/$id'
      fullPath: '/admin/wnioski/$id'
      preLoaderRoute: typeof AdminWnioskiIdRouteImport
      parentRoute: typeof AdminWnioskiRoute
    }
  }
}

interface AdminWnioskiRouteChildren {
  AdminWnioskiIdRoute: typeof AdminWnioskiIdRoute
}

const AdminWnioskiRouteChildren: AdminWnioskiRouteChildren = {
  AdminWnioskiIdRoute: AdminWnioskiIdRoute,
}

const AdminWnioskiRouteWithChildren = AdminWnioskiRoute._addFileChildren(
  AdminWnioskiRouteChildren,
)

interface AdminRouteChildren {
  AdminDokumentyRoute: typeof AdminDokumentyRoute
  AdminFollowUpRoute: typeof AdminFollowUpRoute
  AdminKlienciRoute: typeof AdminKlienciRoute
  AdminLeadyRoute: typeof AdminLeadyRoute
  AdminNieruchomosciRoute: typeof AdminNieruchomosciRoute
  AdminRoleRoute: typeof AdminRoleRoute
  AdminUstawieniaRoute: typeof AdminUstawieniaRoute
  AdminWnioskiRoute: typeof AdminWnioskiRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDokumentyRoute: AdminDokumentyRoute,
  AdminFollowUpRoute: AdminFollowUpRoute,
  AdminKlienciRoute: AdminKlienciRoute,
  AdminLeadyRoute: AdminLeadyRoute,
  AdminNieruchomosciRoute: AdminNieruchomosciRoute,
  AdminRoleRoute: AdminRoleRoute,
  AdminUstawieniaRoute: AdminUstawieniaRoute,
  AdminWnioskiRoute: AdminWnioskiRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InwestorRouteChildren {
  InwestorIndexRoute: typeof InwestorIndexRoute
}

const InwestorRouteChildren: InwestorRouteChildren = {
  InwestorIndexRoute: InwestorIndexRoute,
}

const InwestorRouteWithChildren = InwestorRoute._addFileChildren(
  InwestorRouteChildren,
)

interface KlientRouteChildren {
  KlientIndexRoute: typeof KlientIndexRoute
}

const KlientRouteChildren: KlientRouteChildren = {
  KlientIndexRoute: KlientIndexRoute,
}

const KlientRouteWithChildren =
  KlientRoute._addFileChildren(KlientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InwestorRoute: InwestorRouteWithChildren,
  KlientRoute: KlientRouteWithChildren,
  LogowanieRoute: LogowanieRoute,
  RejestracjaRoute: RejestracjaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
