/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WyborRoliRouteImport } from './routes/wybor-roli'
import { Route as RejestracjaRouteImport } from './routes/rejestracja'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as KlientRouteImport } from './routes/klient'
import { Route as InwestorRouteImport } from './routes/inwestor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlientIndexRouteImport } from './routes/klient.index'
import { Route as InwestorIndexRouteImport } from './routes/inwestor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WniosekTokenRouteImport } from './routes/wniosek.$token'
import { Route as KlientWiadomosciRouteImport } from './routes/klient.wiadomosci'
import { Route as KlientStatusRouteImport } from './routes/klient.status'
import { Route as KlientProfilRouteImport } from './routes/klient.profil'
import { Route as KlientOfertaRouteImport } from './routes/klient.oferta'
import { Route as KlientKontaktRouteImport } from './routes/klient.kontakt'
import { Route as KlientDokumentyRouteImport } from './routes/klient.dokumenty'
import { Route as InwestorWiadomosciRouteImport } from './routes/inwestor.wiadomosci'
import { Route as InwestorSzkoleniaRouteImport } from './routes/inwestor.szkolenia'
import { Route as InwestorProfilRouteImport } from './routes/inwestor.profil'
import { Route as InwestorOfertyRouteImport } from './routes/inwestor.oferty'
import { Route as InwestorKalkulatorRouteImport } from './routes/inwestor.kalkulator'
import { Route as InwestorAbonamentRouteImport } from './routes/inwestor.abonament'
import { Route as EmbedWniosekRouteImport } from './routes/embed.wniosek'
import { Route as AdminWnioskiRouteImport } from './routes/admin.wnioski'
import { Route as AdminVoicebotRouteImport } from './routes/admin.voicebot'
import { Route as AdminUstawieniaRouteImport } from './routes/admin.ustawienia'
import { Route as AdminSzkoleniaRouteImport } from './routes/admin.szkolenia'
import { Route as AdminRoleRouteImport } from './routes/admin.role'
import { Route as AdminOfertyRouteImport } from './routes/admin.oferty'
import { Route as AdminLeadyRouteImport } from './routes/admin.leady'
import { Route as AdminKreatorPozyczkiRouteImport } from './routes/admin.kreator-pozyczki'
import { Route as AdminKlienciRouteImport } from './routes/admin.klienci'
import { Route as AdminInwestorzyRouteImport } from './routes/admin.inwestorzy'
import { Route as AdminIntegracjeRouteImport } from './routes/admin.integracje'
import { Route as AdminFollowUpRouteImport } from './routes/admin.follow-up'
import { Route as AdminFakturowoRouteImport } from './routes/admin.fakturowo'
import { Route as AdminEmbedRouteImport } from './routes/admin.embed'
import { Route as AdminDystrybucjaRouteImport } from './routes/admin.dystrybucja'
import { Route as AdminDokumentyRouteImport } from './routes/admin.dokumenty'
import { Route as KlientUmowaOfferIdRouteImport } from './routes/klient.umowa.$offerId'
import { Route as InwestorWniosekIdRouteImport } from './routes/inwestor.wniosek.$id'
import { Route as InwestorUmowaOfferIdRouteImport } from './routes/inwestor.umowa.$offerId'
import { Route as ApiPublicLoanApplicationRouteImport } from './routes/api/public/loan-application'
import { Route as ApiPublicElevenlabsWebhookRouteImport } from './routes/api/public/elevenlabs-webhook'
import { Route as AdminWnioskiIdRouteImport } from './routes/admin.wnioski.$id'
import { Route as AdminInwestorzyIdRouteImport } from './routes/admin.inwestorzy.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WyborRoliRoute = WyborRoliRouteImport.update({
  id: '/wybor-roli',
  path: '/wybor-roli',
  getParentRoute: () => rootRouteImport,
} as any)
const RejestracjaRoute = RejestracjaRouteImport.update({
  id: '/rejestracja',
  path: '/rejestracja',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientRoute = KlientRouteImport.update({
  id: '/klient',
  path: '/klient',
  getParentRoute: () => rootRouteImport,
} as any)
const InwestorRoute = InwestorRouteImport.update({
  id: '/inwestor',
  path: '/inwestor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientIndexRoute = KlientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KlientRoute,
} as any)
const InwestorIndexRoute = InwestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InwestorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WniosekTokenRoute = WniosekTokenRouteImport.update({
  id: '/wniosek/$token',
  path: '/wniosek/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const KlientWiadomosciRoute = KlientWiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => KlientRoute,
} as any)
const KlientStatusRoute = KlientStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => KlientRoute,
} as any)
const KlientProfilRoute = KlientProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => KlientRoute,
} as any)
const KlientOfertaRoute = KlientOfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => KlientRoute,
} as any)
const KlientKontaktRoute = KlientKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => KlientRoute,
} as any)
const KlientDokumentyRoute = KlientDokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => KlientRoute,
} as any)
const InwestorWiadomosciRoute = InwestorWiadomosciRouteImport.update({
  id: '/wiadomosci',
  path: '/wiadomosci',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorSzkoleniaRoute = InwestorSzkoleniaRouteImport.update({
  id: '/szkolenia',
  path: '/szkolenia',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorProfilRoute = InwestorProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorOfertyRoute = InwestorOfertyRouteImport.update({
  id: '/oferty',
  path: '/oferty',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorKalkulatorRoute = InwestorKalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorAbonamentRoute = InwestorAbonamentRouteImport.update({
  id: '/abonament',
  path: '/abonament',
  getParentRoute: () => InwestorRoute,
} as any)
const EmbedWniosekRoute = EmbedWniosekRouteImport.update({
  id: '/embed/wniosek',
  path: '/embed/wniosek',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWnioskiRoute = AdminWnioskiRouteImport.update({
  id: '/wnioski',
  path: '/wnioski',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoicebotRoute = AdminVoicebotRouteImport.update({
  id: '/voicebot',
  path: '/voicebot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUstawieniaRoute = AdminUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSzkoleniaRoute = AdminSzkoleniaRouteImport.update({
  id: '/szkolenia',
  path: '/szkolenia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoleRoute = AdminRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfertyRoute = AdminOfertyRouteImport.update({
  id: '/oferty',
  path: '/oferty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadyRoute = AdminLeadyRouteImport.update({
  id: '/leady',
  path: '/leady',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKreatorPozyczkiRoute = AdminKreatorPozyczkiRouteImport.update({
  id: '/kreator-pozyczki',
  path: '/kreator-pozyczki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKlienciRoute = AdminKlienciRouteImport.update({
  id: '/klienci',
  path: '/klienci',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInwestorzyRoute = AdminInwestorzyRouteImport.update({
  id: '/inwestorzy',
  path: '/inwestorzy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracjeRoute = AdminIntegracjeRouteImport.update({
  id: '/integracje',
  path: '/integracje',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFollowUpRoute = AdminFollowUpRouteImport.update({
  id: '/follow-up',
  path: '/follow-up',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFakturowoRoute = AdminFakturowoRouteImport.update({
  id: '/fakturowo',
  path: '/fakturowo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmbedRoute = AdminEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDystrybucjaRoute = AdminDystrybucjaRouteImport.update({
  id: '/dystrybucja',
  path: '/dystrybucja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDokumentyRoute = AdminDokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => AdminRoute,
} as any)
const KlientUmowaOfferIdRoute = KlientUmowaOfferIdRouteImport.update({
  id: '/umowa/$offerId',
  path: '/umowa/$offerId',
  getParentRoute: () => KlientRoute,
} as any)
const InwestorWniosekIdRoute = InwestorWniosekIdRouteImport.update({
  id: '/wniosek/$id',
  path: '/wniosek/$id',
  getParentRoute: () => InwestorRoute,
} as any)
const InwestorUmowaOfferIdRoute = InwestorUmowaOfferIdRouteImport.update({
  id: '/umowa/$offerId',
  path: '/umowa/$offerId',
  getParentRoute: () => InwestorRoute,
} as any)
const ApiPublicLoanApplicationRoute =
  ApiPublicLoanApplicationRouteImport.update({
    id: '/api/public/loan-application',
    path: '/api/public/loan-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicElevenlabsWebhookRoute =
  ApiPublicElevenlabsWebhookRouteImport.update({
    id: '/api/public/elevenlabs-webhook',
    path: '/api/public/elevenlabs-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWnioskiIdRoute = AdminWnioskiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWnioskiRoute,
} as any)
const AdminInwestorzyIdRoute = AdminInwestorzyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInwestorzyRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inwestor': typeof InwestorRouteWithChildren
  '/klient': typeof KlientRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/wybor-roli': typeof WyborRoliRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/dystrybucja': typeof AdminDystrybucjaRoute
  '/admin/embed': typeof AdminEmbedRoute
  '/admin/fakturowo': typeof AdminFakturowoRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/integracje': typeof AdminIntegracjeRoute
  '/admin/inwestorzy': typeof AdminInwestorzyRouteWithChildren
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/kreator-pozyczki': typeof AdminKreatorPozyczkiRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/oferty': typeof AdminOfertyRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/szkolenia': typeof AdminSzkoleniaRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/voicebot': typeof AdminVoicebotRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/embed/wniosek': typeof EmbedWniosekRoute
  '/inwestor/abonament': typeof InwestorAbonamentRoute
  '/inwestor/kalkulator': typeof InwestorKalkulatorRoute
  '/inwestor/oferty': typeof InwestorOfertyRoute
  '/inwestor/profil': typeof InwestorProfilRoute
  '/inwestor/szkolenia': typeof InwestorSzkoleniaRoute
  '/inwestor/wiadomosci': typeof InwestorWiadomosciRoute
  '/klient/dokumenty': typeof KlientDokumentyRoute
  '/klient/kontakt': typeof KlientKontaktRoute
  '/klient/oferta': typeof KlientOfertaRoute
  '/klient/profil': typeof KlientProfilRoute
  '/klient/status': typeof KlientStatusRoute
  '/klient/wiadomosci': typeof KlientWiadomosciRoute
  '/wniosek/$token': typeof WniosekTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/inwestor/': typeof InwestorIndexRoute
  '/klient/': typeof KlientIndexRoute
  '/admin/inwestorzy/$id': typeof AdminInwestorzyIdRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/loan-application': typeof ApiPublicLoanApplicationRoute
  '/inwestor/umowa/$offerId': typeof InwestorUmowaOfferIdRoute
  '/inwestor/wniosek/$id': typeof InwestorWniosekIdRoute
  '/klient/umowa/$offerId': typeof KlientUmowaOfferIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/wybor-roli': typeof WyborRoliRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/dystrybucja': typeof AdminDystrybucjaRoute
  '/admin/embed': typeof AdminEmbedRoute
  '/admin/fakturowo': typeof AdminFakturowoRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/integracje': typeof AdminIntegracjeRoute
  '/admin/inwestorzy': typeof AdminInwestorzyRouteWithChildren
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/kreator-pozyczki': typeof AdminKreatorPozyczkiRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/oferty': typeof AdminOfertyRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/szkolenia': typeof AdminSzkoleniaRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/voicebot': typeof AdminVoicebotRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/embed/wniosek': typeof EmbedWniosekRoute
  '/inwestor/abonament': typeof InwestorAbonamentRoute
  '/inwestor/kalkulator': typeof InwestorKalkulatorRoute
  '/inwestor/oferty': typeof InwestorOfertyRoute
  '/inwestor/profil': typeof InwestorProfilRoute
  '/inwestor/szkolenia': typeof InwestorSzkoleniaRoute
  '/inwestor/wiadomosci': typeof InwestorWiadomosciRoute
  '/klient/dokumenty': typeof KlientDokumentyRoute
  '/klient/kontakt': typeof KlientKontaktRoute
  '/klient/oferta': typeof KlientOfertaRoute
  '/klient/profil': typeof KlientProfilRoute
  '/klient/status': typeof KlientStatusRoute
  '/klient/wiadomosci': typeof KlientWiadomosciRoute
  '/wniosek/$token': typeof WniosekTokenRoute
  '/admin': typeof AdminIndexRoute
  '/inwestor': typeof InwestorIndexRoute
  '/klient': typeof KlientIndexRoute
  '/admin/inwestorzy/$id': typeof AdminInwestorzyIdRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/loan-application': typeof ApiPublicLoanApplicationRoute
  '/inwestor/umowa/$offerId': typeof InwestorUmowaOfferIdRoute
  '/inwestor/wniosek/$id': typeof InwestorWniosekIdRoute
  '/klient/umowa/$offerId': typeof KlientUmowaOfferIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/inwestor': typeof InwestorRouteWithChildren
  '/klient': typeof KlientRouteWithChildren
  '/logowanie': typeof LogowanieRoute
  '/rejestracja': typeof RejestracjaRoute
  '/wybor-roli': typeof WyborRoliRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/dystrybucja': typeof AdminDystrybucjaRoute
  '/admin/embed': typeof AdminEmbedRoute
  '/admin/fakturowo': typeof AdminFakturowoRoute
  '/admin/follow-up': typeof AdminFollowUpRoute
  '/admin/integracje': typeof AdminIntegracjeRoute
  '/admin/inwestorzy': typeof AdminInwestorzyRouteWithChildren
  '/admin/klienci': typeof AdminKlienciRoute
  '/admin/kreator-pozyczki': typeof AdminKreatorPozyczkiRoute
  '/admin/leady': typeof AdminLeadyRoute
  '/admin/oferty': typeof AdminOfertyRoute
  '/admin/role': typeof AdminRoleRoute
  '/admin/szkolenia': typeof AdminSzkoleniaRoute
  '/admin/ustawienia': typeof AdminUstawieniaRoute
  '/admin/voicebot': typeof AdminVoicebotRoute
  '/admin/wnioski': typeof AdminWnioskiRouteWithChildren
  '/embed/wniosek': typeof EmbedWniosekRoute
  '/inwestor/abonament': typeof InwestorAbonamentRoute
  '/inwestor/kalkulator': typeof InwestorKalkulatorRoute
  '/inwestor/oferty': typeof InwestorOfertyRoute
  '/inwestor/profil': typeof InwestorProfilRoute
  '/inwestor/szkolenia': typeof InwestorSzkoleniaRoute
  '/inwestor/wiadomosci': typeof InwestorWiadomosciRoute
  '/klient/dokumenty': typeof KlientDokumentyRoute
  '/klient/kontakt': typeof KlientKontaktRoute
  '/klient/oferta': typeof KlientOfertaRoute
  '/klient/profil': typeof KlientProfilRoute
  '/klient/status': typeof KlientStatusRoute
  '/klient/wiadomosci': typeof KlientWiadomosciRoute
  '/wniosek/$token': typeof WniosekTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/inwestor/': typeof InwestorIndexRoute
  '/klient/': typeof KlientIndexRoute
  '/admin/inwestorzy/$id': typeof AdminInwestorzyIdRoute
  '/admin/wnioski/$id': typeof AdminWnioskiIdRoute
  '/api/public/elevenlabs-webhook': typeof ApiPublicElevenlabsWebhookRoute
  '/api/public/loan-application': typeof ApiPublicLoanApplicationRoute
  '/inwestor/umowa/$offerId': typeof InwestorUmowaOfferIdRoute
  '/inwestor/wniosek/$id': typeof InwestorWniosekIdRoute
  '/klient/umowa/$offerId': typeof KlientUmowaOfferIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/logowanie'
    | '/rejestracja'
    | '/wybor-roli'
    | '/admin/dokumenty'
    | '/admin/dystrybucja'
    | '/admin/embed'
    | '/admin/fakturowo'
    | '/admin/follow-up'
    | '/admin/integracje'
    | '/admin/inwestorzy'
    | '/admin/klienci'
    | '/admin/kreator-pozyczki'
    | '/admin/leady'
    | '/admin/oferty'
    | '/admin/role'
    | '/admin/szkolenia'
    | '/admin/ustawienia'
    | '/admin/voicebot'
    | '/admin/wnioski'
    | '/embed/wniosek'
    | '/inwestor/abonament'
    | '/inwestor/kalkulator'
    | '/inwestor/oferty'
    | '/inwestor/profil'
    | '/inwestor/szkolenia'
    | '/inwestor/wiadomosci'
    | '/klient/dokumenty'
    | '/klient/kontakt'
    | '/klient/oferta'
    | '/klient/profil'
    | '/klient/status'
    | '/klient/wiadomosci'
    | '/wniosek/$token'
    | '/admin/'
    | '/inwestor/'
    | '/klient/'
    | '/admin/inwestorzy/$id'
    | '/admin/wnioski/$id'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/loan-application'
    | '/inwestor/umowa/$offerId'
    | '/inwestor/wniosek/$id'
    | '/klient/umowa/$offerId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logowanie'
    | '/rejestracja'
    | '/wybor-roli'
    | '/admin/dokumenty'
    | '/admin/dystrybucja'
    | '/admin/embed'
    | '/admin/fakturowo'
    | '/admin/follow-up'
    | '/admin/integracje'
    | '/admin/inwestorzy'
    | '/admin/klienci'
    | '/admin/kreator-pozyczki'
    | '/admin/leady'
    | '/admin/oferty'
    | '/admin/role'
    | '/admin/szkolenia'
    | '/admin/ustawienia'
    | '/admin/voicebot'
    | '/admin/wnioski'
    | '/embed/wniosek'
    | '/inwestor/abonament'
    | '/inwestor/kalkulator'
    | '/inwestor/oferty'
    | '/inwestor/profil'
    | '/inwestor/szkolenia'
    | '/inwestor/wiadomosci'
    | '/klient/dokumenty'
    | '/klient/kontakt'
    | '/klient/oferta'
    | '/klient/profil'
    | '/klient/status'
    | '/klient/wiadomosci'
    | '/wniosek/$token'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/admin/inwestorzy/$id'
    | '/admin/wnioski/$id'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/loan-application'
    | '/inwestor/umowa/$offerId'
    | '/inwestor/wniosek/$id'
    | '/klient/umowa/$offerId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/inwestor'
    | '/klient'
    | '/logowanie'
    | '/rejestracja'
    | '/wybor-roli'
    | '/admin/dokumenty'
    | '/admin/dystrybucja'
    | '/admin/embed'
    | '/admin/fakturowo'
    | '/admin/follow-up'
    | '/admin/integracje'
    | '/admin/inwestorzy'
    | '/admin/klienci'
    | '/admin/kreator-pozyczki'
    | '/admin/leady'
    | '/admin/oferty'
    | '/admin/role'
    | '/admin/szkolenia'
    | '/admin/ustawienia'
    | '/admin/voicebot'
    | '/admin/wnioski'
    | '/embed/wniosek'
    | '/inwestor/abonament'
    | '/inwestor/kalkulator'
    | '/inwestor/oferty'
    | '/inwestor/profil'
    | '/inwestor/szkolenia'
    | '/inwestor/wiadomosci'
    | '/klient/dokumenty'
    | '/klient/kontakt'
    | '/klient/oferta'
    | '/klient/profil'
    | '/klient/status'
    | '/klient/wiadomosci'
    | '/wniosek/$token'
    | '/admin/'
    | '/inwestor/'
    | '/klient/'
    | '/admin/inwestorzy/$id'
    | '/admin/wnioski/$id'
    | '/api/public/elevenlabs-webhook'
    | '/api/public/loan-application'
    | '/inwestor/umowa/$offerId'
    | '/inwestor/wniosek/$id'
    | '/klient/umowa/$offerId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InwestorRoute: typeof InwestorRouteWithChildren
  KlientRoute: typeof KlientRouteWithChildren
  LogowanieRoute: typeof LogowanieRoute
  RejestracjaRoute: typeof RejestracjaRoute
  WyborRoliRoute: typeof WyborRoliRoute
  EmbedWniosekRoute: typeof EmbedWniosekRoute
  WniosekTokenRoute: typeof WniosekTokenRoute
  ApiPublicElevenlabsWebhookRoute: typeof ApiPublicElevenlabsWebhookRoute
  ApiPublicLoanApplicationRoute: typeof ApiPublicLoanApplicationRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wybor-roli': {
      id: '/wybor-roli'
      path: '/wybor-roli'
      fullPath: '/wybor-roli'
      preLoaderRoute: typeof WyborRoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejestracja': {
      id: '/rejestracja'
      path: '/rejestracja'
      fullPath: '/rejestracja'
      preLoaderRoute: typeof RejestracjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient': {
      id: '/klient'
      path: '/klient'
      fullPath: '/klient'
      preLoaderRoute: typeof KlientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inwestor': {
      id: '/inwestor'
      path: '/inwestor'
      fullPath: '/inwestor'
      preLoaderRoute: typeof InwestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient/': {
      id: '/klient/'
      path: '/'
      fullPath: '/klient/'
      preLoaderRoute: typeof KlientIndexRouteImport
      parentRoute: typeof KlientRoute
    }
    '/inwestor/': {
      id: '/inwestor/'
      path: '/'
      fullPath: '/inwestor/'
      preLoaderRoute: typeof InwestorIndexRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wniosek/$token': {
      id: '/wniosek/$token'
      path: '/wniosek/$token'
      fullPath: '/wniosek/$token'
      preLoaderRoute: typeof WniosekTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klient/wiadomosci': {
      id: '/klient/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/klient/wiadomosci'
      preLoaderRoute: typeof KlientWiadomosciRouteImport
      parentRoute: typeof KlientRoute
    }
    '/klient/status': {
      id: '/klient/status'
      path: '/status'
      fullPath: '/klient/status'
      preLoaderRoute: typeof KlientStatusRouteImport
      parentRoute: typeof KlientRoute
    }
    '/klient/profil': {
      id: '/klient/profil'
      path: '/profil'
      fullPath: '/klient/profil'
      preLoaderRoute: typeof KlientProfilRouteImport
      parentRoute: typeof KlientRoute
    }
    '/klient/oferta': {
      id: '/klient/oferta'
      path: '/oferta'
      fullPath: '/klient/oferta'
      preLoaderRoute: typeof KlientOfertaRouteImport
      parentRoute: typeof KlientRoute
    }
    '/klient/kontakt': {
      id: '/klient/kontakt'
      path: '/kontakt'
      fullPath: '/klient/kontakt'
      preLoaderRoute: typeof KlientKontaktRouteImport
      parentRoute: typeof KlientRoute
    }
    '/klient/dokumenty': {
      id: '/klient/dokumenty'
      path: '/dokumenty'
      fullPath: '/klient/dokumenty'
      preLoaderRoute: typeof KlientDokumentyRouteImport
      parentRoute: typeof KlientRoute
    }
    '/inwestor/wiadomosci': {
      id: '/inwestor/wiadomosci'
      path: '/wiadomosci'
      fullPath: '/inwestor/wiadomosci'
      preLoaderRoute: typeof InwestorWiadomosciRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/szkolenia': {
      id: '/inwestor/szkolenia'
      path: '/szkolenia'
      fullPath: '/inwestor/szkolenia'
      preLoaderRoute: typeof InwestorSzkoleniaRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/profil': {
      id: '/inwestor/profil'
      path: '/profil'
      fullPath: '/inwestor/profil'
      preLoaderRoute: typeof InwestorProfilRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/oferty': {
      id: '/inwestor/oferty'
      path: '/oferty'
      fullPath: '/inwestor/oferty'
      preLoaderRoute: typeof InwestorOfertyRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/kalkulator': {
      id: '/inwestor/kalkulator'
      path: '/kalkulator'
      fullPath: '/inwestor/kalkulator'
      preLoaderRoute: typeof InwestorKalkulatorRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/abonament': {
      id: '/inwestor/abonament'
      path: '/abonament'
      fullPath: '/inwestor/abonament'
      preLoaderRoute: typeof InwestorAbonamentRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/embed/wniosek': {
      id: '/embed/wniosek'
      path: '/embed/wniosek'
      fullPath: '/embed/wniosek'
      preLoaderRoute: typeof EmbedWniosekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wnioski': {
      id: '/admin/wnioski'
      path: '/wnioski'
      fullPath: '/admin/wnioski'
      preLoaderRoute: typeof AdminWnioskiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voicebot': {
      id: '/admin/voicebot'
      path: '/voicebot'
      fullPath: '/admin/voicebot'
      preLoaderRoute: typeof AdminVoicebotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ustawienia': {
      id: '/admin/ustawienia'
      path: '/ustawienia'
      fullPath: '/admin/ustawienia'
      preLoaderRoute: typeof AdminUstawieniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/szkolenia': {
      id: '/admin/szkolenia'
      path: '/szkolenia'
      fullPath: '/admin/szkolenia'
      preLoaderRoute: typeof AdminSzkoleniaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/role': {
      id: '/admin/role'
      path: '/role'
      fullPath: '/admin/role'
      preLoaderRoute: typeof AdminRoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oferty': {
      id: '/admin/oferty'
      path: '/oferty'
      fullPath: '/admin/oferty'
      preLoaderRoute: typeof AdminOfertyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leady': {
      id: '/admin/leady'
      path: '/leady'
      fullPath: '/admin/leady'
      preLoaderRoute: typeof AdminLeadyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kreator-pozyczki': {
      id: '/admin/kreator-pozyczki'
      path: '/kreator-pozyczki'
      fullPath: '/admin/kreator-pozyczki'
      preLoaderRoute: typeof AdminKreatorPozyczkiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/klienci': {
      id: '/admin/klienci'
      path: '/klienci'
      fullPath: '/admin/klienci'
      preLoaderRoute: typeof AdminKlienciRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inwestorzy': {
      id: '/admin/inwestorzy'
      path: '/inwestorzy'
      fullPath: '/admin/inwestorzy'
      preLoaderRoute: typeof AdminInwestorzyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracje': {
      id: '/admin/integracje'
      path: '/integracje'
      fullPath: '/admin/integracje'
      preLoaderRoute: typeof AdminIntegracjeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/follow-up': {
      id: '/admin/follow-up'
      path: '/follow-up'
      fullPath: '/admin/follow-up'
      preLoaderRoute: typeof AdminFollowUpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fakturowo': {
      id: '/admin/fakturowo'
      path: '/fakturowo'
      fullPath: '/admin/fakturowo'
      preLoaderRoute: typeof AdminFakturowoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/embed': {
      id: '/admin/embed'
      path: '/embed'
      fullPath: '/admin/embed'
      preLoaderRoute: typeof AdminEmbedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dystrybucja': {
      id: '/admin/dystrybucja'
      path: '/dystrybucja'
      fullPath: '/admin/dystrybucja'
      preLoaderRoute: typeof AdminDystrybucjaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dokumenty': {
      id: '/admin/dokumenty'
      path: '/dokumenty'
      fullPath: '/admin/dokumenty'
      preLoaderRoute: typeof AdminDokumentyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/klient/umowa/$offerId': {
      id: '/klient/umowa/$offerId'
      path: '/umowa/$offerId'
      fullPath: '/klient/umowa/$offerId'
      preLoaderRoute: typeof KlientUmowaOfferIdRouteImport
      parentRoute: typeof KlientRoute
    }
    '/inwestor/wniosek/$id': {
      id: '/inwestor/wniosek/$id'
      path: '/wniosek/$id'
      fullPath: '/inwestor/wniosek/$id'
      preLoaderRoute: typeof InwestorWniosekIdRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/inwestor/umowa/$offerId': {
      id: '/inwestor/umowa/$offerId'
      path: '/umowa/$offerId'
      fullPath: '/inwestor/umowa/$offerId'
      preLoaderRoute: typeof InwestorUmowaOfferIdRouteImport
      parentRoute: typeof InwestorRoute
    }
    '/api/public/loan-application': {
      id: '/api/public/loan-application'
      path: '/api/public/loan-application'
      fullPath: '/api/public/loan-application'
      preLoaderRoute: typeof ApiPublicLoanApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/elevenlabs-webhook': {
      id: '/api/public/elevenlabs-webhook'
      path: '/api/public/elevenlabs-webhook'
      fullPath: '/api/public/elevenlabs-webhook'
      preLoaderRoute: typeof ApiPublicElevenlabsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wnioski/$id': {
      id: '/admin/wnioski/$id'
      path: '/$id'
      fullPath: '/admin/wnioski/$id'
      preLoaderRoute: typeof AdminWnioskiIdRouteImport
      parentRoute: typeof AdminWnioskiRoute
    }
    '/admin/inwestorzy/$id': {
      id: '/admin/inwestorzy/$id'
      path: '/$id'
      fullPath: '/admin/inwestorzy/$id'
      preLoaderRoute: typeof AdminInwestorzyIdRouteImport
      parentRoute: typeof AdminInwestorzyRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminInwestorzyRouteChildren {
  AdminInwestorzyIdRoute: typeof AdminInwestorzyIdRoute
}

const AdminInwestorzyRouteChildren: AdminInwestorzyRouteChildren = {
  AdminInwestorzyIdRoute: AdminInwestorzyIdRoute,
}

const AdminInwestorzyRouteWithChildren = AdminInwestorzyRoute._addFileChildren(
  AdminInwestorzyRouteChildren,
)

interface AdminWnioskiRouteChildren {
  AdminWnioskiIdRoute: typeof AdminWnioskiIdRoute
}

const AdminWnioskiRouteChildren: AdminWnioskiRouteChildren = {
  AdminWnioskiIdRoute: AdminWnioskiIdRoute,
}

const AdminWnioskiRouteWithChildren = AdminWnioskiRoute._addFileChildren(
  AdminWnioskiRouteChildren,
)

interface AdminRouteChildren {
  AdminDokumentyRoute: typeof AdminDokumentyRoute
  AdminDystrybucjaRoute: typeof AdminDystrybucjaRoute
  AdminEmbedRoute: typeof AdminEmbedRoute
  AdminFakturowoRoute: typeof AdminFakturowoRoute
  AdminFollowUpRoute: typeof AdminFollowUpRoute
  AdminIntegracjeRoute: typeof AdminIntegracjeRoute
  AdminInwestorzyRoute: typeof AdminInwestorzyRouteWithChildren
  AdminKlienciRoute: typeof AdminKlienciRoute
  AdminKreatorPozyczkiRoute: typeof AdminKreatorPozyczkiRoute
  AdminLeadyRoute: typeof AdminLeadyRoute
  AdminOfertyRoute: typeof AdminOfertyRoute
  AdminRoleRoute: typeof AdminRoleRoute
  AdminSzkoleniaRoute: typeof AdminSzkoleniaRoute
  AdminUstawieniaRoute: typeof AdminUstawieniaRoute
  AdminVoicebotRoute: typeof AdminVoicebotRoute
  AdminWnioskiRoute: typeof AdminWnioskiRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDokumentyRoute: AdminDokumentyRoute,
  AdminDystrybucjaRoute: AdminDystrybucjaRoute,
  AdminEmbedRoute: AdminEmbedRoute,
  AdminFakturowoRoute: AdminFakturowoRoute,
  AdminFollowUpRoute: AdminFollowUpRoute,
  AdminIntegracjeRoute: AdminIntegracjeRoute,
  AdminInwestorzyRoute: AdminInwestorzyRouteWithChildren,
  AdminKlienciRoute: AdminKlienciRoute,
  AdminKreatorPozyczkiRoute: AdminKreatorPozyczkiRoute,
  AdminLeadyRoute: AdminLeadyRoute,
  AdminOfertyRoute: AdminOfertyRoute,
  AdminRoleRoute: AdminRoleRoute,
  AdminSzkoleniaRoute: AdminSzkoleniaRoute,
  AdminUstawieniaRoute: AdminUstawieniaRoute,
  AdminVoicebotRoute: AdminVoicebotRoute,
  AdminWnioskiRoute: AdminWnioskiRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InwestorRouteChildren {
  InwestorAbonamentRoute: typeof InwestorAbonamentRoute
  InwestorKalkulatorRoute: typeof InwestorKalkulatorRoute
  InwestorOfertyRoute: typeof InwestorOfertyRoute
  InwestorProfilRoute: typeof InwestorProfilRoute
  InwestorSzkoleniaRoute: typeof InwestorSzkoleniaRoute
  InwestorWiadomosciRoute: typeof InwestorWiadomosciRoute
  InwestorIndexRoute: typeof InwestorIndexRoute
  InwestorUmowaOfferIdRoute: typeof InwestorUmowaOfferIdRoute
  InwestorWniosekIdRoute: typeof InwestorWniosekIdRoute
}

const InwestorRouteChildren: InwestorRouteChildren = {
  InwestorAbonamentRoute: InwestorAbonamentRoute,
  InwestorKalkulatorRoute: InwestorKalkulatorRoute,
  InwestorOfertyRoute: InwestorOfertyRoute,
  InwestorProfilRoute: InwestorProfilRoute,
  InwestorSzkoleniaRoute: InwestorSzkoleniaRoute,
  InwestorWiadomosciRoute: InwestorWiadomosciRoute,
  InwestorIndexRoute: InwestorIndexRoute,
  InwestorUmowaOfferIdRoute: InwestorUmowaOfferIdRoute,
  InwestorWniosekIdRoute: InwestorWniosekIdRoute,
}

const InwestorRouteWithChildren = InwestorRoute._addFileChildren(
  InwestorRouteChildren,
)

interface KlientRouteChildren {
  KlientDokumentyRoute: typeof KlientDokumentyRoute
  KlientKontaktRoute: typeof KlientKontaktRoute
  KlientOfertaRoute: typeof KlientOfertaRoute
  KlientProfilRoute: typeof KlientProfilRoute
  KlientStatusRoute: typeof KlientStatusRoute
  KlientWiadomosciRoute: typeof KlientWiadomosciRoute
  KlientIndexRoute: typeof KlientIndexRoute
  KlientUmowaOfferIdRoute: typeof KlientUmowaOfferIdRoute
}

const KlientRouteChildren: KlientRouteChildren = {
  KlientDokumentyRoute: KlientDokumentyRoute,
  KlientKontaktRoute: KlientKontaktRoute,
  KlientOfertaRoute: KlientOfertaRoute,
  KlientProfilRoute: KlientProfilRoute,
  KlientStatusRoute: KlientStatusRoute,
  KlientWiadomosciRoute: KlientWiadomosciRoute,
  KlientIndexRoute: KlientIndexRoute,
  KlientUmowaOfferIdRoute: KlientUmowaOfferIdRoute,
}

const KlientRouteWithChildren =
  KlientRoute._addFileChildren(KlientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InwestorRoute: InwestorRouteWithChildren,
  KlientRoute: KlientRouteWithChildren,
  LogowanieRoute: LogowanieRoute,
  RejestracjaRoute: RejestracjaRoute,
  WyborRoliRoute: WyborRoliRoute,
  EmbedWniosekRoute: EmbedWniosekRoute,
  WniosekTokenRoute: WniosekTokenRoute,
  ApiPublicElevenlabsWebhookRoute: ApiPublicElevenlabsWebhookRoute,
  ApiPublicLoanApplicationRoute: ApiPublicLoanApplicationRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
