-- Słownik kodów wydziałów ksiąg wieczystych → sąd rejonowy (pkt 2 zlecenia
-- „przypadki graniczne wniosek → KW → umowa”). Źródło: załącznik do
-- rozporządzenia Ministra Sprawiedliwości z 28.10.2019 r. (Dz.U. 2019 poz. 2222),
-- „Oznaczenia kodów wydziałów ksiąg wieczystych sądów rejonowych” (345 kodów,
-- w mocy od 01.12.2019). Ta sama lista jest w src/lib/kw-court-codes.ts (używana
-- przez silnik bez zapytania do bazy) — zmiany wprowadzaj w obu miejscach.

CREATE TABLE IF NOT EXISTS public.kw_court_codes (
  code text PRIMARY KEY CHECK (code ~ '^[A-Z]{2}[0-9][A-Z]$'),
  court_name text NOT NULL,
  department text,
  scope text,
  source text NOT NULL DEFAULT 'Dz.U. 2019 poz. 2222',
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.kw_court_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "kw_court_codes read" ON public.kw_court_codes;
CREATE POLICY "kw_court_codes read" ON public.kw_court_codes
  FOR SELECT TO authenticated USING (true);

INSERT INTO public.kw_court_codes (code, court_name, department, scope) VALUES
  ('BI1B', 'Sąd Rejonowy w Białymstoku', NULL, NULL),
  ('BI1P', 'Sąd Rejonowy w Bielsku Podlaskim', NULL, NULL),
  ('BI2P', 'Sąd Rejonowy w Bielsku Podlaskim', 'Wydział Zamiejscowy z siedzibą w Hajnówce', NULL),
  ('BI3P', 'Sąd Rejonowy w Bielsku Podlaskim', 'Wydział Zamiejscowy z siedzibą w Siemiatyczach', NULL),
  ('BI1S', 'Sąd Rejonowy w Sokółce', NULL, NULL),
  ('LM1G', 'Sąd Rejonowy w Grajewie', NULL, NULL),
  ('LM1L', 'Sąd Rejonowy w Łomży', NULL, NULL),
  ('LM1W', 'Sąd Rejonowy w Wysokiem Mazowieckiem', NULL, NULL),
  ('LM1Z', 'Sąd Rejonowy w Zambrowie', NULL, NULL),
  ('OL1Y', 'Sąd Rejonowy w Bartoszycach', NULL, NULL),
  ('OL1B', 'Sąd Rejonowy w Biskupcu', NULL, NULL),
  ('OL1G', 'Sąd Rejonowy w Giżycku', NULL, NULL),
  ('OL2G', 'Sąd Rejonowy w Giżycku', 'Wydział Zamiejscowy z siedzibą w Węgorzewie', NULL),
  ('OL1K', 'Sąd Rejonowy w Kętrzynie', NULL, NULL),
  ('OL1L', 'Sąd Rejonowy w Lidzbarku Warmińskim', NULL, NULL),
  ('OL1M', 'Sąd Rejonowy w Mrągowie', NULL, NULL),
  ('OL1N', 'Sąd Rejonowy w Nidzicy', NULL, NULL),
  ('OL1O', 'Sąd Rejonowy w Olsztynie', NULL, NULL),
  ('OL1P', 'Sąd Rejonowy w Piszu', NULL, NULL),
  ('OL1S', 'Sąd Rejonowy w Szczytnie', NULL, NULL),
  ('OS1O', 'Sąd Rejonowy w Ostrołęce', NULL, NULL),
  ('OS1M', 'Sąd Rejonowy w Ostrowi Mazowieckiej', NULL, NULL),
  ('OS1P', 'Sąd Rejonowy w Przasnyszu', NULL, NULL),
  ('OS1U', 'Sąd Rejonowy w Pułtusku', NULL, NULL),
  ('OS1W', 'Sąd Rejonowy w Wyszkowie', NULL, NULL),
  ('SU1A', 'Sąd Rejonowy w Augustowie', NULL, NULL),
  ('SU1N', 'Sąd Rejonowy w Augustowie', 'Wydział Zamiejscowy z siedzibą w Sejnach', NULL),
  ('OL1E', 'Sąd Rejonowy w Ełku', NULL, NULL),
  ('OL1C', 'Sąd Rejonowy w Olecku', NULL, NULL),
  ('SU1S', 'Sąd Rejonowy w Suwałkach', NULL, NULL),
  ('BY1B', 'Sąd Rejonowy w Bydgoszczy', NULL, NULL),
  ('BY1I', 'Sąd Rejonowy w Inowrocławiu', NULL, NULL),
  ('BY1M', 'Sąd Rejonowy w Mogilnie', NULL, NULL),
  ('BY1N', 'Sąd Rejonowy w Nakle nad Notecią', NULL, NULL),
  ('BY1U', 'Sąd Rejonowy w Szubinie', NULL, NULL),
  ('BY1S', 'Sąd Rejonowy w Świeciu', NULL, NULL),
  ('BY1T', 'Sąd Rejonowy w Tucholi', NULL, NULL),
  ('BY2T', 'Sąd Rejonowy w Tucholi', 'Wydział Zamiejscowy z siedzibą w Sępólnie Krajeńskim', NULL),
  ('BY1Z', 'Sąd Rejonowy w Żninie', NULL, NULL),
  ('EL1B', 'Sąd Rejonowy w Braniewie', NULL, NULL),
  ('EL1D', 'Sąd Rejonowy w Działdowie', NULL, NULL),
  ('EL1E', 'Sąd Rejonowy w Elblągu', NULL, NULL),
  ('EL1I', 'Sąd Rejonowy w Iławie', NULL, NULL),
  ('EL1N', 'Sąd Rejonowy w Nowym Mieście Lubawskim', NULL, NULL),
  ('EL1O', 'Sąd Rejonowy w Ostródzie', NULL, NULL),
  ('EL2O', 'Sąd Rejonowy w Ostródzie', 'Wydział Zamiejscowy z siedzibą w Morągu', NULL),
  ('GD1G', 'Sąd Rejonowy Gdańsk-Północ w Gdańsku', NULL, NULL),
  ('GD1Y', 'Sąd Rejonowy w Gdyni', NULL, NULL),
  ('GD1R', 'Sąd Rejonowy w Kartuzach', NULL, NULL),
  ('GD1E', 'Sąd Rejonowy w Kościerzynie', NULL, NULL),
  ('GD1I', 'Sąd Rejonowy w Kwidzynie', NULL, NULL),
  ('GD2I', 'Sąd Rejonowy w Kwidzynie', 'Wydział Zamiejscowy z siedzibą w Sztumie', NULL),
  ('GD1M', 'Sąd Rejonowy w Malborku', NULL, NULL),
  ('GD2M', 'Sąd Rejonowy w Malborku', 'Wydział Zamiejscowy z siedzibą w Nowym Dworze Gdańskim', NULL),
  ('GD1S', 'Sąd Rejonowy w Sopocie', NULL, NULL),
  ('GD1A', 'Sąd Rejonowy w Starogardzie Gdańskim', NULL, NULL),
  ('GD1T', 'Sąd Rejonowy w Tczewie', NULL, NULL),
  ('GD1W', 'Sąd Rejonowy w Wejherowie', NULL, NULL),
  ('GD2W', 'Sąd Rejonowy w Wejherowie', 'Wydział Zamiejscowy z siedzibą w Pucku', NULL),
  ('SL1B', 'Sąd Rejonowy w Bytowie', NULL, NULL),
  ('SL1C', 'Sąd Rejonowy w Chojnicach', NULL, NULL),
  ('SL1Z', 'Sąd Rejonowy w Człuchowie', NULL, NULL),
  ('SL1L', 'Sąd Rejonowy w Lęborku', NULL, NULL),
  ('SL1M', 'Sąd Rejonowy w Miastku', NULL, NULL),
  ('SL1S', 'Sąd Rejonowy w Słupsku', NULL, NULL),
  ('TO1B', 'Sąd Rejonowy w Brodnicy', NULL, NULL),
  ('TO1C', 'Sąd Rejonowy w Chełmnie', NULL, NULL),
  ('TO1G', 'Sąd Rejonowy w Golubiu-Dobrzyniu', NULL, NULL),
  ('TO1U', 'Sąd Rejonowy w Grudziądzu', NULL, NULL),
  ('TO1T', 'Sąd Rejonowy w Toruniu', NULL, NULL),
  ('TO1W', 'Sąd Rejonowy w Wąbrzeźnie', NULL, NULL),
  ('WL1A', 'Sąd Rejonowy w Aleksandrowie Kujawskim', NULL, NULL),
  ('WL1L', 'Sąd Rejonowy w Lipnie', NULL, NULL),
  ('WL1R', 'Sąd Rejonowy w Radziejowie', NULL, NULL),
  ('WL1Y', 'Sąd Rejonowy w Rypinie', NULL, NULL),
  ('WL1W', 'Sąd Rejonowy we Włocławku', NULL, NULL),
  ('BB1B', 'Sąd Rejonowy w Bielsku-Białej', NULL, NULL),
  ('BB1C', 'Sąd Rejonowy w Cieszynie', NULL, NULL),
  ('BB1Z', 'Sąd Rejonowy w Żywcu', NULL, NULL),
  ('CZ1C', 'Sąd Rejonowy w Częstochowie', NULL, NULL),
  ('CZ2C', 'Sąd Rejonowy w Częstochowie', 'Wydział Zamiejscowy z siedzibą w Kłobucku', NULL),
  ('CZ1L', 'Sąd Rejonowy w Lublińcu', NULL, NULL),
  ('CZ1M', 'Sąd Rejonowy w Myszkowie', NULL, NULL),
  ('CZ1Z', 'Sąd Rejonowy w Zawierciu', NULL, NULL),
  ('GL1G', 'Sąd Rejonowy w Gliwicach', NULL, NULL),
  ('GL1J', 'Sąd Rejonowy w Jastrzębiu-Zdroju', NULL, NULL),
  ('GL1R', 'Sąd Rejonowy w Raciborzu', NULL, NULL),
  ('GL1S', 'Sąd Rejonowy w Rudzie Śląskiej', NULL, NULL),
  ('GL1Y', 'Sąd Rejonowy w Rybniku', NULL, NULL),
  ('GL1T', 'Sąd Rejonowy w Tarnowskich Górach', NULL, NULL),
  ('GL1W', 'Sąd Rejonowy w Wodzisławiu Śląskim', NULL, NULL),
  ('GL1Z', 'Sąd Rejonowy w Zabrzu', NULL, NULL),
  ('GL1X', 'Sąd Rejonowy w Żorach', NULL, NULL),
  ('KA1B', 'Sąd Rejonowy w Będzinie', NULL, NULL),
  ('KA1Y', 'Sąd Rejonowy w Bytomiu', NULL, NULL),
  ('KA1C', 'Sąd Rejonowy w Chorzowie', NULL, NULL),
  ('KA1D', 'Sąd Rejonowy w Dąbrowie Górniczej', NULL, NULL),
  ('KA1J', 'Sąd Rejonowy w Jaworznie', NULL, NULL),
  ('KA1K', 'Sąd Rejonowy Katowice-Wschód w Katowicach', NULL, NULL),
  ('KA1M', 'Sąd Rejonowy w Mikołowie', NULL, NULL),
  ('KA1L', 'Sąd Rejonowy w Mysłowicach', NULL, NULL),
  ('KA1P', 'Sąd Rejonowy w Pszczynie', NULL, NULL),
  ('KA1I', 'Sąd Rejonowy w Siemianowicach Śląskich', NULL, NULL),
  ('KA1S', 'Sąd Rejonowy w Sosnowcu', NULL, NULL),
  ('KA1T', 'Sąd Rejonowy w Tychach', NULL, NULL),
  ('KI1B', 'Sąd Rejonowy w Busku-Zdroju', NULL, NULL),
  ('KI1I', 'Sąd Rejonowy w Busku-Zdroju', 'Wydział Zamiejscowy z siedzibą w Kazimierzy Wielkiej', NULL),
  ('KI1J', 'Sąd Rejonowy w Jędrzejowie', NULL, NULL),
  ('KI1L', 'Sąd Rejonowy w Kielcach', NULL, NULL),
  ('KI1K', 'Sąd Rejonowy w Końskich', NULL, NULL),
  ('KI1T', 'Sąd Rejonowy w Opatowie', NULL, NULL),
  ('KI1O', 'Sąd Rejonowy w Ostrowcu Świętokrzyskim', NULL, NULL),
  ('KI1P', 'Sąd Rejonowy w Pińczowie', NULL, NULL),
  ('KI1S', 'Sąd Rejonowy w Sandomierzu', NULL, NULL),
  ('KI1R', 'Sąd Rejonowy w Skarżysku-Kamiennej', NULL, NULL),
  ('KI1H', 'Sąd Rejonowy w Starachowicach', NULL, NULL),
  ('KI1A', 'Sąd Rejonowy w Staszowie', NULL, NULL),
  ('KI1W', 'Sąd Rejonowy we Włoszczowie', NULL, NULL),
  ('KR1C', 'Sąd Rejonowy w Chrzanowie', NULL, NULL),
  ('KR1K', 'Sąd Rejonowy dla Krakowa-Krowodrzy w Krakowie', 'Wydział Zamiejscowy z siedzibą w Czernichowie', NULL),
  ('KR2K', 'Sąd Rejonowy dla Krakowa-Krowodrzy w Krakowie', 'Wydział Zamiejscowy z siedzibą w Krzeszowicach', NULL),
  ('KR1H', 'Sąd Rejonowy dla Krakowa-Nowej Huty w Krakowie', 'Wydział Zamiejscowy z siedzibą w Proszowicach', NULL),
  ('KR1P', 'Sąd Rejonowy dla Krakowa-Podgórza w Krakowie', NULL, NULL),
  ('KR2P', 'Sąd Rejonowy dla Krakowa-Podgórza w Krakowie', 'Wydział Zamiejscowy z siedzibą w Skale', NULL),
  ('KR1M', 'Sąd Rejonowy w Miechowie', NULL, NULL),
  ('KR1S', 'Sąd Rejonowy w Miechowie', 'Wydział Zamiejscowy z siedzibą w Słomnikach', NULL),
  ('KR1Y', 'Sąd Rejonowy w Myślenicach', NULL, NULL),
  ('KR2Y', 'Sąd Rejonowy w Myślenicach', 'Wydział Zamiejscowy z siedzibą w Dobczycach', NULL),
  ('KR1O', 'Sąd Rejonowy w Olkuszu', NULL, NULL),
  ('KR1E', 'Sąd Rejonowy w Oświęcimiu', NULL, NULL),
  ('KR2E', 'Sąd Rejonowy w Oświęcimiu', 'Wydział Zamiejscowy z siedzibą w Kętach', NULL),
  ('KR1B', 'Sąd Rejonowy w Suchej Beskidzkiej', NULL, NULL),
  ('KR1W', 'Sąd Rejonowy w Wadowicach', NULL, NULL),
  ('KR1I', 'Sąd Rejonowy w Wieliczce', NULL, NULL),
  ('KR2I', 'Sąd Rejonowy w Wieliczce', 'Wydział Zamiejscowy z siedzibą w Niepołomicach', NULL),
  ('KR3I', 'Sąd Rejonowy w Wieliczce', 'Wydział Zamiejscowy z siedzibą w Skawinie', NULL),
  ('NS1G', 'Sąd Rejonowy w Gorlicach', NULL, NULL),
  ('NS1L', 'Sąd Rejonowy w Limanowej', NULL, NULL),
  ('NS2L', 'Sąd Rejonowy w Limanowej', 'Wydział Zamiejscowy z siedzibą w Mszanie Dolnej', NULL),
  ('NS1S', 'Sąd Rejonowy w Nowym Sączu', NULL, NULL),
  ('NS1M', 'Sąd Rejonowy w Nowym Sączu', 'Wydział Zamiejscowy z siedzibą w Muszynie', NULL),
  ('NS1T', 'Sąd Rejonowy w Nowym Targu', NULL, NULL),
  ('NS1Z', 'Sąd Rejonowy w Zakopanem', NULL, NULL),
  ('TR1O', 'Sąd Rejonowy w Bochni', NULL, NULL),
  ('TR1B', 'Sąd Rejonowy w Brzesku', NULL, NULL),
  ('TR1D', 'Sąd Rejonowy w Dąbrowie Tarnowskiej', NULL, NULL),
  ('TR1T', 'Sąd Rejonowy w Tarnowie', NULL, NULL),
  ('TR2T', 'Sąd Rejonowy w Tarnowie', 'Wydział Zamiejscowy z siedzibą w Tuchowie', NULL),
  ('LU1B', 'Sąd Rejonowy w Białej Podlaskiej', NULL, NULL),
  ('LU1C', 'Sąd Rejonowy w Chełmie', NULL, NULL),
  ('LU1K', 'Sąd Rejonowy w Kraśniku', NULL, NULL),
  ('LU1A', 'Sąd Rejonowy w Lubartowie', NULL, NULL),
  ('LU1S', 'Sąd Rejonowy Lublin-Wschód w Lublinie z siedzibą w Świdniku', NULL, NULL),
  ('LU1I', 'Sąd Rejonowy Lublin-Zachód w Lublinie', NULL, NULL),
  ('LU1O', 'Sąd Rejonowy w Opolu Lubelskim', NULL, NULL),
  ('LU1P', 'Sąd Rejonowy w Puławach', NULL, NULL),
  ('LU1R', 'Sąd Rejonowy w Radzyniu Podlaskim', NULL, NULL),
  ('LU1Y', 'Sąd Rejonowy w Rykach', NULL, NULL),
  ('LU1W', 'Sąd Rejonowy we Włodawie', NULL, NULL),
  ('RA1G', 'Sąd Rejonowy w Grójcu', NULL, NULL),
  ('RA2G', 'Sąd Rejonowy w Grójcu', 'Wydział Zamiejscowy z siedzibą w Białobrzegach', NULL),
  ('RA1K', 'Sąd Rejonowy w Kozienicach', NULL, NULL),
  ('RA1L', 'Sąd Rejonowy w Lipsku', NULL, NULL),
  ('RA1P', 'Sąd Rejonowy w Przysusze', NULL, NULL),
  ('RA1R', 'Sąd Rejonowy w Radomiu', NULL, NULL),
  ('RA1S', 'Sąd Rejonowy w Szydłowcu', NULL, NULL),
  ('RA1Z', 'Sąd Rejonowy w Zwoleniu', NULL, NULL),
  ('SI1G', 'Sąd Rejonowy w Garwolinie', NULL, NULL),
  ('LU1U', 'Sąd Rejonowy w Łukowie', NULL, NULL),
  ('SI1M', 'Sąd Rejonowy w Mińsku Mazowieckim', NULL, NULL),
  ('SI1S', 'Sąd Rejonowy w Siedlcach', NULL, NULL),
  ('SI2S', 'Sąd Rejonowy w Siedlcach', 'Wydział Zamiejscowy z siedzibą w Łosicach', NULL),
  ('SI1P', 'Sąd Rejonowy w Sokołowie Podlaskim', NULL, NULL),
  ('SI1W', 'Sąd Rejonowy w Węgrowie', NULL, NULL),
  ('ZA1B', 'Sąd Rejonowy w Biłgoraju', NULL, NULL),
  ('ZA1H', 'Sąd Rejonowy w Hrubieszowie', NULL, NULL),
  ('ZA1J', 'Sąd Rejonowy w Janowie Lubelskim', NULL, NULL),
  ('ZA1K', 'Sąd Rejonowy w Krasnymstawie', NULL, NULL),
  ('ZA1T', 'Sąd Rejonowy w Tomaszowie Lubelskim', NULL, NULL),
  ('ZA1Z', 'Sąd Rejonowy w Zamościu', NULL, NULL),
  ('KZ1J', 'Sąd Rejonowy w Jarocinie', NULL, NULL),
  ('KZ1A', 'Sąd Rejonowy w Kaliszu', NULL, NULL),
  ('KZ1E', 'Sąd Rejonowy w Kępnie', NULL, NULL),
  ('KZ1R', 'Sąd Rejonowy w Krotoszynie', NULL, NULL),
  ('KZ1W', 'Sąd Rejonowy w Ostrowie Wielkopolskim', NULL, NULL),
  ('KZ1O', 'Sąd Rejonowy w Ostrzeszowie', NULL, NULL),
  ('KZ1P', 'Sąd Rejonowy w Pleszewie', NULL, NULL),
  ('LD1B', 'Sąd Rejonowy w Brzezinach', NULL, NULL),
  ('LD1K', 'Sąd Rejonowy w Kutnie', NULL, NULL),
  ('LD1Y', 'Sąd Rejonowy w Łęczycy', NULL, NULL),
  ('LD1M', 'Sąd Rejonowy dla Łodzi-Śródmieścia w Łodzi', NULL, NULL),
  ('LD1O', 'Sąd Rejonowy w Łowiczu', NULL, NULL),
  ('LD1P', 'Sąd Rejonowy w Pabianicach', NULL, NULL),
  ('LD1R', 'Sąd Rejonowy w Rawie Mazowieckiej', NULL, NULL),
  ('LD1H', 'Sąd Rejonowy w Skierniewicach', NULL, NULL),
  ('LD1G', 'Sąd Rejonowy w Zgierzu', NULL, NULL),
  ('PT1B', 'Sąd Rejonowy w Bełchatowie', NULL, NULL),
  ('PT1O', 'Sąd Rejonowy w Opocznie', NULL, NULL),
  ('PT1P', 'Sąd Rejonowy w Piotrkowie Trybunalskim', NULL, NULL),
  ('PT1R', 'Sąd Rejonowy w Radomsku', NULL, NULL),
  ('PT1T', 'Sąd Rejonowy w Tomaszowie Mazowieckim', NULL, NULL),
  ('PL1C', 'Sąd Rejonowy w Ciechanowie', NULL, NULL),
  ('PL1G', 'Sąd Rejonowy w Gostyninie', NULL, NULL),
  ('PL1M', 'Sąd Rejonowy w Mławie', NULL, NULL),
  ('PL2M', 'Sąd Rejonowy w Mławie', 'Wydział Zamiejscowy z siedzibą w Żurominie', NULL),
  ('PL1P', 'Sąd Rejonowy w Płocku', NULL, NULL),
  ('PL1L', 'Sąd Rejonowy w Płońsku', NULL, NULL),
  ('PL1E', 'Sąd Rejonowy w Sierpcu', NULL, NULL),
  ('PL1O', 'Sąd Rejonowy w Sochaczewie', NULL, NULL),
  ('PL1Z', 'Sąd Rejonowy w Żyrardowie', NULL, NULL),
  ('SR1L', 'Sąd Rejonowy w Łasku', NULL, NULL),
  ('SR2L', 'Sąd Rejonowy w Łasku', 'Wydział Zamiejscowy z siedzibą w Poddębicach', NULL),
  ('SR1S', 'Sąd Rejonowy w Sieradzu', NULL, NULL),
  ('SR1W', 'Sąd Rejonowy w Wieluniu', NULL, NULL),
  ('SR2W', 'Sąd Rejonowy w Wieluniu', 'Wydział Zamiejscowy z siedzibą w Pajęcznie', NULL),
  ('SR1Z', 'Sąd Rejonowy w Zduńskiej Woli', NULL, NULL),
  ('KN1K', 'Sąd Rejonowy w Kole', NULL, NULL),
  ('KN1N', 'Sąd Rejonowy w Koninie', NULL, NULL),
  ('KN1S', 'Sąd Rejonowy w Słupcy', NULL, NULL),
  ('KN1T', 'Sąd Rejonowy w Turku', NULL, NULL),
  ('PO1H', 'Sąd Rejonowy w Chodzieży', NULL, NULL),
  ('PO2H', 'Sąd Rejonowy w Chodzieży', 'Wydział Zamiejscowy z siedzibą w Wyrzysku', NULL),
  ('PO1G', 'Sąd Rejonowy w Gnieźnie', NULL, NULL),
  ('PO1Y', 'Sąd Rejonowy w Gostyniu', NULL, NULL),
  ('PO1S', 'Sąd Rejonowy w Grodzisku Wielkopolskim', NULL, NULL),
  ('PO1K', 'Sąd Rejonowy w Kościanie', NULL, NULL),
  ('PO1L', 'Sąd Rejonowy w Lesznie', NULL, NULL),
  ('PO1N', 'Sąd Rejonowy w Nowym Tomyślu', NULL, NULL),
  ('PO1O', 'Sąd Rejonowy w Obornikach', NULL, NULL),
  ('PO1I', 'Sąd Rejonowy w Pile', NULL, NULL),
  ('PO1P', 'Sąd Rejonowy Poznań-Stare Miasto w Poznaniu', NULL, 'dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Grunwald, Jeżyce i Stare Miasto oraz gmin: Czerwonak, Dopiewo, Murowana Goślina, Suchy Las i Tarnowo Podgórne'),
  ('PO2P', 'Sąd Rejonowy Poznań-Stare Miasto w Poznaniu', NULL, 'dla części miasta Poznania w granicach ustalonych tradycyjnie dla dzielnic: Nowe Miasto i Wilda, miast Luboń i Puszczykowo oraz gmin Komorniki i Swarzędz'),
  ('PO1R', 'Sąd Rejonowy w Rawiczu', NULL, NULL),
  ('PO1A', 'Sąd Rejonowy w Szamotułach', NULL, NULL),
  ('PO2A', 'Sąd Rejonowy w Szamotułach', 'Wydział Zamiejscowy z siedzibą w Międzychodzie', NULL),
  ('PO1M', 'Sąd Rejonowy w Śremie', NULL, NULL),
  ('PO1D', 'Sąd Rejonowy w Środzie Wielkopolskiej', NULL, NULL),
  ('PO1T', 'Sąd Rejonowy w Trzciance', NULL, NULL),
  ('PO2T', 'Sąd Rejonowy w Trzciance', 'Wydział Zamiejscowy z siedzibą w Czarnkowie', NULL),
  ('PO1B', 'Sąd Rejonowy w Wągrowcu', NULL, NULL),
  ('PO1E', 'Sąd Rejonowy w Wolsztynie', NULL, NULL),
  ('PO1F', 'Sąd Rejonowy we Wrześni', NULL, NULL),
  ('PO1Z', 'Sąd Rejonowy w Złotowie', NULL, NULL),
  ('ZG1K', 'Sąd Rejonowy w Krośnie Odrzańskim', NULL, NULL),
  ('ZG2K', 'Sąd Rejonowy w Krośnie Odrzańskim', 'Wydział Zamiejscowy z siedzibą w Gubinie', NULL),
  ('ZG1N', 'Sąd Rejonowy w Nowej Soli', NULL, NULL),
  ('ZG1S', 'Sąd Rejonowy w Świebodzinie', NULL, NULL),
  ('ZG2S', 'Sąd Rejonowy w Świebodzinie', 'Wydział Zamiejscowy z siedzibą w Sulechowie', NULL),
  ('ZG1W', 'Sąd Rejonowy we Wschowie', NULL, NULL),
  ('ZG1E', 'Sąd Rejonowy w Zielonej Górze', NULL, NULL),
  ('ZG1G', 'Sąd Rejonowy w Żaganiu', NULL, NULL),
  ('ZG1R', 'Sąd Rejonowy w Żarach', NULL, NULL),
  ('KS1B', 'Sąd Rejonowy w Brzozowie', NULL, NULL),
  ('KS1J', 'Sąd Rejonowy w Jaśle', NULL, NULL),
  ('KS1K', 'Sąd Rejonowy w Krośnie', NULL, NULL),
  ('KS1E', 'Sąd Rejonowy w Lesku', NULL, NULL),
  ('KS2E', 'Sąd Rejonowy w Lesku', 'Wydział Zamiejscowy z siedzibą w Ustrzykach Dolnych', NULL),
  ('KS1S', 'Sąd Rejonowy w Sanoku', NULL, NULL),
  ('PR1J', 'Sąd Rejonowy w Jarosławiu', NULL, NULL),
  ('PR1L', 'Sąd Rejonowy w Lubaczowie', NULL, NULL),
  ('PR1P', 'Sąd Rejonowy w Przemyślu', NULL, NULL),
  ('PR1R', 'Sąd Rejonowy w Przeworsku', NULL, NULL),
  ('PR2R', 'Sąd Rejonowy w Przeworsku', 'Wydział Zamiejscowy z siedzibą w Sieniawie', NULL),
  ('RZ1D', 'Sąd Rejonowy w Dębicy', NULL, NULL),
  ('RZ1E', 'Sąd Rejonowy w Leżajsku', NULL, NULL),
  ('RZ1A', 'Sąd Rejonowy w Łańcucie', NULL, NULL),
  ('RZ1R', 'Sąd Rejonowy w Ropczycach', NULL, NULL),
  ('RZ1Z', 'Sąd Rejonowy w Rzeszowie', NULL, NULL),
  ('RZ2Z', 'Sąd Rejonowy w Rzeszowie', 'Wydział Zamiejscowy z siedzibą w Tyczynie', NULL),
  ('RZ1S', 'Sąd Rejonowy w Strzyżowie', NULL, NULL),
  ('TB1K', 'Sąd Rejonowy w Kolbuszowej', NULL, NULL),
  ('TB1M', 'Sąd Rejonowy w Mielcu', NULL, NULL),
  ('TB1N', 'Sąd Rejonowy w Nisku', NULL, NULL),
  ('TB1S', 'Sąd Rejonowy w Stalowej Woli', NULL, NULL),
  ('TB1T', 'Sąd Rejonowy w Tarnobrzegu', NULL, NULL),
  ('GW1G', 'Sąd Rejonowy w Gorzowie Wielkopolskim', NULL, NULL),
  ('GW1M', 'Sąd Rejonowy w Międzyrzeczu', NULL, NULL),
  ('GW1S', 'Sąd Rejonowy w Słubicach', NULL, NULL),
  ('GW1K', 'Sąd Rejonowy w Strzelcach Krajeńskich', NULL, NULL),
  ('GW1U', 'Sąd Rejonowy w Sulęcinie', NULL, NULL),
  ('KO1B', 'Sąd Rejonowy w Białogardzie', NULL, NULL),
  ('KO2B', 'Sąd Rejonowy w Białogardzie', 'Wydział Zamiejscowy z siedzibą w Świdwinie', NULL),
  ('KO1D', 'Sąd Rejonowy w Drawsku Pomorskim', NULL, NULL),
  ('KO1L', 'Sąd Rejonowy w Kołobrzegu', NULL, NULL),
  ('KO1K', 'Sąd Rejonowy w Koszalinie', NULL, NULL),
  ('KO1E', 'Sąd Rejonowy w Sławnie', NULL, NULL),
  ('KO1I', 'Sąd Rejonowy w Szczecinku', NULL, NULL),
  ('KO1W', 'Sąd Rejonowy w Wałczu', NULL, NULL),
  ('SZ1C', 'Sąd Rejonowy w Choszcznie', NULL, NULL),
  ('SZ1O', 'Sąd Rejonowy w Goleniowie', NULL, NULL),
  ('SZ1G', 'Sąd Rejonowy w Gryficach', NULL, NULL),
  ('SZ1K', 'Sąd Rejonowy w Kamieniu Pomorskim', NULL, NULL),
  ('SZ1L', 'Sąd Rejonowy w Łobzie', NULL, NULL),
  ('SZ1Y', 'Sąd Rejonowy w Gryfinie', NULL, NULL),
  ('SZ1M', 'Sąd Rejonowy w Myśliborzu', NULL, NULL),
  ('SZ1T', 'Sąd Rejonowy w Stargardzie', NULL, NULL),
  ('SZ2T', 'Sąd Rejonowy w Stargardzie', 'Wydział Zamiejscowy z siedzibą w Pyrzycach', NULL),
  ('SZ1S', 'Sąd Rejonowy Szczecin-Prawobrzeże i Zachód w Szczecinie', NULL, NULL),
  ('SZ2S', 'Sąd Rejonowy Szczecin-Prawobrzeże i Zachód w Szczecinie', 'Wydział Zamiejscowy z siedzibą w Policach', NULL),
  ('SZ1W', 'Sąd Rejonowy w Świnoujściu', NULL, NULL),
  ('WA1G', 'Sąd Rejonowy w Grodzisku Mazowieckim', NULL, NULL),
  ('WA1I', 'Sąd Rejonowy w Piasecznie', NULL, NULL),
  ('WA1P', 'Sąd Rejonowy w Pruszkowie', NULL, NULL),
  ('WA1M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Bemowo, Bielany, Ochota i Żoliborz oraz gminy Izabelin'),
  ('WA2M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Mokotów i Wilanów'),
  ('WA3M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Białołęka, Praga-Północ, Targówek'),
  ('WA4M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic Śródmieście i Wola oraz gminy Łomianki'),
  ('WA5M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Ursus, Ursynów i Włochy'),
  ('WA6M', 'Sąd Rejonowy dla Warszawy-Mokotowa w Warszawie', NULL, 'dla części miasta stołecznego Warszawy w granicach ustalonych dla dzielnic: Praga-Południe, Rembertów, Wawer i Wesoła'),
  ('WA1L', 'Sąd Rejonowy Sąd Okręgowy Warszawa-Praga w Warszawie WP w Legionowie', NULL, NULL),
  ('WA1N', 'Sąd Rejonowy w Nowym Dworze Mazowieckim', NULL, NULL),
  ('WA1O', 'Sąd Rejonowy w Otwocku', NULL, NULL),
  ('WA1W', 'Sąd Rejonowy w Wołominie', NULL, NULL),
  ('JG1B', 'Sąd Rejonowy w Bolesławcu', NULL, NULL),
  ('JG1J', 'Sąd Rejonowy w Jeleniej Górze', NULL, NULL),
  ('JG1K', 'Sąd Rejonowy w Kamiennej Górze', NULL, NULL),
  ('JG1L', 'Sąd Rejonowy w Lubaniu', NULL, NULL),
  ('JG1S', 'Sąd Rejonowy w Lwówku Śląskim', NULL, NULL),
  ('JG1Z', 'Sąd Rejonowy w Zgorzelcu', NULL, NULL),
  ('LE1G', 'Sąd Rejonowy w Głogowie', NULL, NULL),
  ('LE1J', 'Sąd Rejonowy w Jaworze', NULL, NULL),
  ('LE1L', 'Sąd Rejonowy w Legnicy', NULL, NULL),
  ('LE1U', 'Sąd Rejonowy w Lubinie', NULL, NULL),
  ('LE1Z', 'Sąd Rejonowy w Złotoryi', NULL, NULL),
  ('OP1B', 'Sąd Rejonowy w Brzegu', NULL, NULL),
  ('OP1G', 'Sąd Rejonowy w Głubczycach', NULL, NULL),
  ('OP1K', 'Sąd Rejonowy w Kędzierzynie-Koźlu', NULL, NULL),
  ('OP1U', 'Sąd Rejonowy w Kluczborku', NULL, NULL),
  ('OP1N', 'Sąd Rejonowy w Nysie', NULL, NULL),
  ('OP1L', 'Sąd Rejonowy w Oleśnie', NULL, NULL),
  ('OP1O', 'Sąd Rejonowy w Opolu', NULL, NULL),
  ('OP1P', 'Sąd Rejonowy w Prudniku', NULL, NULL),
  ('OP1S', 'Sąd Rejonowy w Strzelcach Opolskich', NULL, NULL),
  ('SW1D', 'Sąd Rejonowy w Dzierżoniowie', NULL, NULL),
  ('SW1K', 'Sąd Rejonowy w Kłodzku', NULL, NULL),
  ('SW1S', 'Sąd Rejonowy w Świdnicy', NULL, NULL),
  ('SW1W', 'Sąd Rejonowy w Wałbrzychu', NULL, NULL),
  ('SW1Z', 'Sąd Rejonowy w Ząbkowicach Śląskich', NULL, NULL),
  ('WR1M', 'Sąd Rejonowy w Miliczu', NULL, NULL),
  ('WR1E', 'Sąd Rejonowy w Oleśnicy', NULL, NULL),
  ('WR1O', 'Sąd Rejonowy w Oławie', NULL, NULL),
  ('WR1T', 'Sąd Rejonowy w Strzelinie', NULL, NULL),
  ('WR1S', 'Sąd Rejonowy w Środzie Śląskiej', NULL, NULL),
  ('WR1W', 'Sąd Rejonowy w Trzebnicy', NULL, NULL),
  ('WR1L', 'Sąd Rejonowy w Wołowie', NULL, NULL)
ON CONFLICT (code) DO UPDATE SET
  court_name = EXCLUDED.court_name,
  department = EXCLUDED.department,
  scope = EXCLUDED.scope,
  updated_at = now();
